/**
 * Profile: the metrics, without the widget.
 *
 * The card is a browser and a notebook is not, but almost everything it *shows* is an ordinary
 * roll-up over three fetches — and the notebook can do something the widget cannot. The widget
 * pages one neuron at a time and pays three requests per neuron viewed; `fetch_adjacencies`
 * takes the whole id list at once, so `coda_profile` costs three requests for a hundred neurons
 * as readily as for one. The emitted call passes the pinned neuron because that is what the
 * canvas was showing, and widening it is editing one argument.
 *
 * Ported from `nodes/lib/profileStats.ts`. Four of its rules are easy to lose and each produces
 * a plausible wrong number rather than an error, so each is called out where it is applied.
 */

import { pyStr } from '../py'
import { registerEmitter, registerHelper } from '../registry'
import { profileExportPin } from '../../plans/profile'
import { neuronIds, pySelection } from './common'
import { readWeightProperty } from '../../../nodes/lib/datasetParam'
import { CYPHER_PLACEHOLDERS, profilePropertyQueries } from '../../plans/connectivity'
import { pickedIds } from '../../plans/viewers'

registerEmitter('out.profile', (ctx) => {
  const src = ctx.wired('neurons')

  const c = ctx.wired('dataset')
  const out = ctx.output('out')
  const current = ctx.output('current')
  const minWeight = Math.max(1, Number(ctx.params.minWeight))
  const topN = Number(ctx.params.topN)
  // The card's Count by, as the canvas's own two queries; passed only when it is not the weight,
  // so a profile that never chose one exports exactly the cell it always did.
  const property = readWeightProperty(ctx.params.countBy)
  const queries = property ? profilePropertyQueries(property) : undefined

  ctx.require('pandas')
  const lines: string[] = [`${out} = ${src}`]

  // The pinned row, which is the node's `Current` output.
  const pinned = pickedIds(ctx, 'out.profile')
  if (pinned.note === undefined) {
    lines.push(`${current} = ${out}[${out}['neuronId'].isin(${pySelection(pinned.ids)})]`)
  } else {
    lines.push(...ctx.note(pinned.note), `${current} = ${out}.iloc[0:0]`)
  }

  ctx.helper('coda_profile')
  const grouped = ctx.column('groupBy')
  // `profileExportPin` owns the rule; this owns only how a list of ids is spelled in Python.
  const pin = profileExportPin(pinned.note === undefined ? pinned.ids : [], grouped)
  const ids = pin ? pySelection(pin) : neuronIds(out)

  lines.push(
    ``,
    // Named frames rather than one long table, so each lines up with a tile on the card.
    `_profile = coda_profile(`,
    `    ${ids},`,
    `    client=${c},`,
    `    min_weight=${minWeight},`,
    `    top_n=${topN},`,
    // Counted by an edge property on the card, so every partner frame below is too.
    ...(queries
      ? [
          `    property_queries={`,
          ...(['upstream', 'downstream'] as const).flatMap((way) => [
            `        ${pyStr(way)}: r"""`,
            ...queries[way].split('\n').map((l) => `        ${l}`),
            `        """,`,
          ]),
          `    },`,
        ]
      : []),
    ...(grouped
      ? [
          // The card is grouped, so the frames below are means across each group's members
          // rather than one row per neuron — see `_coda_group_means`.
          `    groups=${out}.set_index('neuronId')[${pyStr(grouped)}],`,
        ]
      : []),
    `)`,
    ``,
    `${ctx.name}_summary = _profile['summary']`,
    `${ctx.name}_upstream_types = _profile['upstream_types']`,
    `${ctx.name}_downstream_types = _profile['downstream_types']`,
    `${ctx.name}_top_upstream = _profile['top_upstream']`,
    `${ctx.name}_top_downstream = _profile['top_downstream']`,
    `${ctx.name}_regions = _profile['regions']`,
    `${ctx.name}_hemispheres = _profile['hemispheres']`,
    ...(grouped
      ? [
          ``,
          // Kept beside the group means rather than replaced by them: the fold is what the card
          // shows, and the per-neuron rows are what says whether a mean is worth trusting.
          `${ctx.name}_upstream_types_by_neuron = _profile['upstream_types_by_neuron']`,
        ]
      : []),
    ``,
    `${ctx.name}_summary`,
  )
  return lines
})

registerHelper({
  name: 'coda_profile',
  // `neurons` and `roi_counts` come straight off `fetch_neurons`, so they arrive carrying
  // neuprint-python's `bodyId` while every roll-up below groups and merges on Coda's
  // `neuronId`. Without the rename each of those is a `KeyError` inside a generated helper.
  needs: ['coda_neurons'],
  requires: [
    ['pandas'],
    [
      'neuprint',
      'NeuronCriteria',
      'fetch_adjacencies',
      'fetch_neurons',
      'fetch_primary_rois',
      'merge_neuron_properties',
      // Only called for Count by, but a helper's imports are its whole body's.
      'fetch_custom',
    ],
  ],
  source: [
    'import re',
    '',
    '_CODA_ROI_SIDE = re.compile(r"\\((L|R)\\)\\s*$")',
    '',
    '',
    'def _coda_roi_side(roi):',
    '    """Return the side of the animal an ROI is on: "L", "R" or "center".',
    '',
    '    neuPrint writes the side as a trailing "(L)" or "(R)", e.g. "HTct(UTct-T3)(L)".',
    '    ROIs without one, such as "ANm" or "CV", are unlateralised.',
    '    """',
    '    match = _CODA_ROI_SIDE.search(roi or "")',
    '    return match.group(1) if match else "center"',
    '',
    '',
    'def _coda_partner_types(conn, top_n):',
    '    """Summarise partners by type: synapse count, partner count and the share of each.',
    '',
    '    Untyped partners are grouped together under a missing type.',
    '    """',
    '    if conn.empty:',
    '        return conn.assign(type=None, synapses=0, partners=0,',
    '                           synapse_share=0.0, partner_share=0.0).iloc[0:0]',
    '',
    '    out = []',
    '    for body, group in conn.groupby("neuronId", sort=False):',
    '        total_syn = group["weight"].sum()',
    '        total_partners = group["partnerId"].nunique()',
    '        rolled = (',
    '            group.groupby("partnerType", dropna=False)',
    '            .agg(synapses=("weight", "sum"), partners=("partnerId", "nunique"))',
    '            .reset_index()',
    '            .rename(columns={"partnerType": "type"})',
    '        )',
    '        rolled["neuronId"] = body',
    '        rolled["synapse_share"] = rolled["synapses"] / total_syn if total_syn else 0.0',
    '        rolled["partner_share"] = (',
    '            rolled["partners"] / total_partners if total_partners else 0.0',
    '        )',
    '        rolled = rolled.sort_values(',
    '            ["synapses", "type"], ascending=[False, True], na_position="last",',
    '        )',
    '        out.append(rolled.head(top_n) if top_n else rolled)',
    '',
    '    cols = ["neuronId", "type", "synapses", "partners", "synapse_share", "partner_share"]',
    '    return pd.concat(out, ignore_index=True)[cols]',
    '',
    '',
    'def _coda_top_partners(conn, top_n):',
    '    """List individual partners, strongest first, with each one\'s share of the synapses."""',
    '    if conn.empty:',
    '        return conn.assign(share=0.0).iloc[0:0]',
    '',
    '    out = []',
    '    for body, group in conn.groupby("neuronId", sort=False):',
    '        total = group["weight"].sum()',
    '        rows = group.copy()',
    '        rows["share"] = rows["weight"] / total if total else 0.0',
    '        rows = rows.sort_values(["weight", "partnerId"], ascending=[False, True])',
    '        out.append(rows.head(top_n) if top_n else rows)',
    '',
    '    cols = ["neuronId", "partnerId", "partnerType", "weight", "share"]',
    '    return pd.concat(out, ignore_index=True)[cols]',
    '',
    '',
    'def _coda_connectivity_by(neuron_ids, query, min_weight, client):',
    '    """Fetch partners in one direction, counted by an edge property instead of the weight.',
    '',
    "    This is the card's `Count by` option (e.g. weightAxonDendrite on fish2). `query` is the",
    `    Cypher Coda sends, with ${CYPHER_PLACEHOLDERS.ids} where the ids go. The property becomes the`,
    '    weight, and min_weight applies to it. Same columns as _coda_connectivity.',
    '    """',
    '    ids = "[" + ", ".join(str(int(i)) for i in neuron_ids) + "]"',
    `    conn = fetch_custom(query.replace("${CYPHER_PLACEHOLDERS.ids}", ids), client=client)`,
    '    conn.columns = ["neuronId", "neuronType", "partnerId", "partnerType", "synapses", "weight"]',
    '    conn = conn[conn["weight"].fillna(0) >= min_weight]',
    '    return conn[["neuronId", "partnerId", "partnerType", "weight"]]',
    '',
    '',
    'def _coda_connectivity(neuron_ids, direction, min_weight, client, weight_query=None):',
    '    """Fetch the partners of the profiled neurons in one direction.',
    '',
    '    neuronId is always the profiled neuron and partnerId the neuron it connects to,',
    "    whichever way the synapse points (unlike Coda's Connectivity node).",
    '    """',
    '    if weight_query is not None:',
    '        return _coda_connectivity_by(neuron_ids, weight_query, min_weight, client)',
    '    criteria = NeuronCriteria(bodyId=list(neuron_ids), client=client)',
    '    if direction == "downstream":',
    '        neurons, conn = fetch_adjacencies(',
    '            criteria, None, min_total_weight=min_weight,',
    '            omit_rois=True, client=client,',
    '        )',
    '        mine, theirs = "bodyId_pre", "bodyId_post"',
    '    else:',
    '        neurons, conn = fetch_adjacencies(',
    '            None, criteria, min_total_weight=min_weight,',
    '            omit_rois=True, client=client,',
    '        )',
    '        mine, theirs = "bodyId_post", "bodyId_pre"',
    '',
    '    if conn.empty:',
    '        return pd.DataFrame(',
    '            columns=["neuronId", "partnerId", "partnerType", "weight"]',
    '        )',
    '',
    '    conn = merge_neuron_properties(neurons, conn, ["type"])',
    '    partner_type = "type_post" if mine == "bodyId_pre" else "type_pre"',
    '    return conn.rename(columns={',
    '        mine: "neuronId", theirs: "partnerId", partner_type: "partnerType",',
    '    })[["neuronId", "partnerId", "partnerType", "weight"]]',
    '',
    '',
    'def _coda_group_means(per_neuron, groups, keys, values):',
    '    """Average per-neuron rows into one row per (group, key).',
    '',
    '    `groups` is a Series indexed by neuronId that assigns each neuron to a group.',
    '',
    '    Every member of a group counts towards the mean, with 0 for members that have no row',
    '    (e.g. a neuron that never connects to partner type X). `<value>_present` gives the',
    '    number of members with a non-zero value. `<value>_sd` is the sample standard',
    '    deviation, NaN for groups of one.',
    '',
    "    Matches the Neuron Profile card (`subjectPartnerTypes` in Coda's profileStats.ts).",
    '    """',
    '    sizes = groups.value_counts()',
    '    df = per_neuron.copy()',
    "    df['group'] = df['neuronId'].map(groups)",
    "    df = df[df['group'].notna()]",
    "    columns = ['group', *keys, 'n']",
    '    for value in values:',
    "        columns += [f'{value}_mean', f'{value}_sd', f'{value}_present']",
    '    if df.empty:',
    '        return pd.DataFrame(columns=columns)',
    '',
    "    by = ['group', *keys]",
    '    grouped = df.groupby(by, dropna=False)',
    "    out = grouped.size().rename('counted').reset_index()",
    "    out['n'] = out['group'].map(sizes)",
    '',
    '    for value in values:',
    '        agg = (',
    '            grouped[value]',
    "            .agg(total='sum', present=lambda s: int((s != 0).sum()))",
    '            .reset_index()',
    '        )',
    "        out = out.merge(agg, on=by, how='left')",
    "        out[f'{value}_mean'] = out['total'] / out['n']",
    '        # Second pass for the deviation. Members without a row each add (0 - mean)^2,',
    '        # which is the (n - counted) term.',
    "        dev = df.merge(out[[*by, f'{value}_mean']], on=by, how='left')",
    "        dev['_d2'] = (dev[value] - dev[f'{value}_mean']) ** 2",
    "        ss = dev.groupby(by, dropna=False)['_d2'].sum().rename('ss').reset_index()",
    "        out = out.merge(ss, on=by, how='left')",
    '        # sd is NaN (not 0) for groups of fewer than two members.',
    "        denom = (out['n'] - 1).where(out['n'] > 1)",
    "        spread = out['ss'] + (out['n'] - out['counted']) * out[f'{value}_mean'] ** 2",
    "        out[f'{value}_sd'] = (spread / denom) ** 0.5",
    "        out = out.rename(columns={'present': f'{value}_present'})",
    "        out = out.drop(columns=['total', 'ss'])",
    '',
    "    return out.drop(columns=['counted'])",
    '',
    '',
    'def _coda_rank(df, by, column, top_n):',
    '    """Sort strongest first within each group and keep the top_n rows (0 keeps all)."""',
    '    df = df.sort_values([*by, column], ascending=[*[True] * len(by), False])',
    '    return df.groupby(by, sort=False).head(top_n) if top_n else df',
    '',
    '',
    'def coda_profile(neuron_ids, client, min_weight=1, top_n=10, groups=None,',
    '                 property_queries=None):',
    '    """Compute what Coda\'s Neuron Profile card shows, as a dict of DataFrames.',
    '',
    '    Keys match the tiles: summary, upstream_types, downstream_types, top_upstream,',
    '    top_downstream, regions, hemispheres.',
    '',
    '    The number of requests does not grow with the number of neurons, so you can profile',
    '    a whole table at once.',
    '',
    '    min_weight drops weaker connections; top_n caps each list (0 keeps all).',
    '',
    "    property_queries counts partners by an edge property instead (the card's `Count by`):",
    '    the two queries Coda sends, keyed "upstream" and "downstream".',
    '',
    '    Pass `groups` (a Series indexed by neuronId) to profile groups such as cell types, as',
    '    the card does with `Group by` set. Each frame then has one row per (group, key) with',
    '    the mean, sample sd and number of contributing members; the per-neuron frames are',
    '    kept under the same names with a `_by_neuron` suffix. See `_coda_group_means`.',
    '    """',
    '    neuron_ids = [int(b) for b in neuron_ids]',
    '    if not neuron_ids:',
    '        empty = pd.DataFrame()',
    '        return {k: empty for k in ("summary", "upstream_types", "downstream_types",',
    '                                   "top_upstream", "top_downstream", "regions",',
    '                                   "hemispheres")}',
    '',
    '    neurons, roi_counts = fetch_neurons(',
    '        NeuronCriteria(bodyId=neuron_ids, client=client), client=client,',
    '    )',
    '    neurons, roi_counts = coda_neurons(neurons), coda_neurons(roi_counts)',
    '    queries = property_queries or {}',
    '    up = _coda_connectivity(neuron_ids, "upstream", min_weight, client, queries.get("upstream"))',
    '    down = _coda_connectivity(',
    '        neuron_ids, "downstream", min_weight, client, queries.get("downstream"),',
    '    )',
    '',
    '    # ROIs are nested (a synapse in LO(R) also counts in OL(R)), so use only the primary',
    '    # ROIs, which do not overlap.',
    '    primary = set(fetch_primary_rois(client=client))',
    '    regions = roi_counts[roi_counts["roi"].isin(primary)].copy()',
    '    regions = (',
    '        regions.groupby(["neuronId", "roi"], as_index=False)[["pre", "post"]].sum()',
    '    )',
    '    regions["total"] = regions["pre"] + regions["post"]',
    '    regions = regions[regions["total"] > 0].sort_values(',
    '        ["neuronId", "total", "roi"], ascending=[True, False, True],',
    '    )',
    '',
    '    sides = regions.assign(side=regions["roi"].map(_coda_roi_side))',
    '    hemispheres = (',
    '        sides.pivot_table(index="neuronId", columns="side", values="total",',
    '                          aggfunc="sum", fill_value=0)',
    '        .rename(columns={"L": "left", "R": "right"})',
    '        .reset_index()',
    '    )',
    '    for column in ("left", "right", "center"):',
    '        if column not in hemispheres:',
    '            hemispheres[column] = 0',
    '    hemispheres["total"] = (',
    '        hemispheres["left"] + hemispheres["right"] + hemispheres["center"]',
    '    )',
    '',
    '    def totals(conn, prefix):',
    '        if conn.empty:',
    '            return pd.DataFrame(columns=["neuronId", f"{prefix}_synapses",',
    '                                         f"{prefix}_partners"])',
    '        return (',
    '            conn.groupby("neuronId", as_index=False)',
    '            .agg(**{f"{prefix}_synapses": ("weight", "sum"),',
    '                    f"{prefix}_partners": ("partnerId", "nunique")})',
    '        )',
    '',
    '    summary = neurons.merge(totals(up, "upstream"), on="neuronId", how="left")',
    '    summary = summary.merge(totals(down, "downstream"), on="neuronId", how="left")',
    '    summary = summary.merge(',
    '        hemispheres[["neuronId", "left", "right", "center"]], on="neuronId", how="left",',
    '    )',
    '',
    "    # When grouping, apply top_n after averaging, not to each member's list.",
    '    cap = 0 if groups is not None else top_n',
    '    out = {',
    '        "summary": summary,',
    '        "upstream_types": _coda_partner_types(up, cap),',
    '        "downstream_types": _coda_partner_types(down, cap),',
    '        "top_upstream": _coda_top_partners(up, cap),',
    '        "top_downstream": _coda_top_partners(down, cap),',
    '        "regions": regions,',
    '        "hemispheres": hemispheres,',
    '    }',
    '    if groups is None:',
    '        return out',
    '',
    '    # Reuse the totals already merged into `summary`.',
    '    summary_totals = summary[[',
    '        "neuronId", "upstream_synapses", "upstream_partners",',
    '        "downstream_synapses", "downstream_partners",',
    '    ]].fillna(0)',
    '',
    '    per_neuron = {f"{k}_by_neuron": v for k, v in out.items()}',
    '    counts = ["synapses", "partners"]',
    '    grouped = {',
    '        "upstream_types": _coda_rank(',
    '            _coda_group_means(out["upstream_types"], groups, ["type"], counts),',
    '            ["group"], "synapses_mean", top_n,',
    '        ),',
    '        "downstream_types": _coda_rank(',
    '            _coda_group_means(out["downstream_types"], groups, ["type"], counts),',
    '            ["group"], "synapses_mean", top_n,',
    '        ),',
    '        # partnerType is part of the key; it is fixed per partnerId, so it splits nothing.',
    '        "top_upstream": _coda_rank(',
    '            _coda_group_means(',
    '                out["top_upstream"], groups, ["partnerId", "partnerType"], ["weight"],',
    '            ),',
    '            ["group"], "weight_mean", top_n,',
    '        ),',
    '        "top_downstream": _coda_rank(',
    '            _coda_group_means(',
    '                out["top_downstream"], groups, ["partnerId", "partnerType"], ["weight"],',
    '            ),',
    '            ["group"], "weight_mean", top_n,',
    '        ),',
    '        "regions": _coda_rank(',
    '            _coda_group_means(regions, groups, ["roi"], ["pre", "post"]),',
    '            ["group"], "pre_mean", 0,',
    '        ),',
    '        # Use the long format: one row per (neuron, side).',
    '        "hemispheres": _coda_group_means(',
    '            sides.groupby(["neuronId", "side"], as_index=False)["total"].sum(),',
    '            groups, ["side"], ["total"],',
    '        ),',
    '        # No key: one row per group.',
    '        "summary": _coda_group_means(',
    '            summary_totals, groups, [],',
    '            ["upstream_synapses", "upstream_partners",',
    '             "downstream_synapses", "downstream_partners"],',
    '        ),',
    '    }',
    '    return {**grouped, **per_neuron}',
  ],
})
