/**
 * `Carry fields`: columns of the incoming neuron table, carried onto the geometry it fetches.
 *
 * A collection's attribute table is **not** the neuron table wired into the node that fetched
 * it. Each source builds its own from `SourceSchemas.morphology` — seven columns on neuPrint
 * (`neuronId`, `type`, `instance`, `status`, `size`, `points`, `cableLength`), three on a CAVE
 * datastack plus whatever its annotation chain publishes, two on a precomputed bucket — and
 * `neuprint/schema.ts` says why it does not follow the dataset: those schemas "are derived from
 * relationships and from `roiInfo`, not from neuron properties, so no dataset varies them". The
 * Neurons input is read for *ids*.
 *
 * That is right until you want to split, colour or group the geometry by something the fetch
 * does not carry. Those columns live on the table one wire back and were unreachable: a
 * connectome publishing 48 neuron properties handed a card seven fields to filter on, and the
 * only route to the other 41 was to filter the table *before* the fetch, which answers a
 * different question (one half, not both) and costs a second fetch to get the other.
 *
 * **What it reaches is what is on that table already** — the dataset's own published properties,
 * an annotation chain's labels, a column a `Relabel` rewrote. Two things it deliberately cannot
 * reach, both for the same reason: the port is `T.neurons()`, so a value typed `table` cannot
 * feed it. A `Cut Tree` cluster table is one (and on the NBLAST route it would be a cycle
 * besides, the clusters being downstream of the geometry), and a `core.join` result is the other
 * — `joinTables` preserves its left input's kind at run time but `core.join`'s `inferOutputs`
 * publishes `T.table` unconditionally, so the obvious "join the extra columns on, then carry
 * them" cannot be wired today. Worth knowing before promising either in prose; the second is one
 * line in `table/join.ts` whenever somebody wants it.
 *
 * ## The join is the Join node's, both halves of it
 *
 * `joinSchema` and `joinTables` are one layout function behind two halves, so carrying inherits
 * every rule already argued there: **duplicate keys annotate, they never multiply** (the right is
 * deduplicated by key, first occurrence winning, so a neuron listed twice upstream does not
 * double its skeleton), a left join keeps the geometry's own row order — which is its *items'*
 * order, the contract everything downstream of a collection rests on — and an id with no row
 * upstream carries nulls rather than dropping the neuron.
 *
 * ## The carried column wins its name, and keeps the old one's slot
 *
 * Two rules, and the second was got wrong first. **Written over, never beside**, which is
 * `foldNodeColumns`' rule and for its reason: a `type_r` beside a `type` gives every downstream
 * picker two answers and the second is the stale one. And **position is preserved**, which is the
 * other half of that function's argument — "a column that moves to the end on every run is a
 * table whose columns reorder when nothing about it changed, which a reader reads as the data
 * having changed". The first draft dismissed that as something nothing reads, which is untrue:
 * `TableViewer` draws `schema.columns` in order, `exportValue` writes a CSV in that order, and
 * GraphML key ids are generated by index over it. So the flagship case — override a stale `type`
 * — would have moved `type` from the second column to the last in every table, viewer and
 * download downstream.
 *
 * `foldNodeColumns` states that shape once and **both halves read it**: the schema half returns
 * it, and the value half reorders the join's output to its column names. So the promise made at
 * edit time and the table built after the fetch cannot come to disagree about either rule.
 *
 * ## Empty carries nothing, and is the exact shape of today's answer
 *
 * The fast path matters beyond speed: with no columns chosen the fetched value is handed back
 * untouched and the schema by identity, so a graph saved before this param existed produces
 * byte-identical geometry rather than a table that has been through a join and back. The list
 * *is* in the provenance key — it changes what `evaluate` returns — so adding a column re-runs
 * the fetch; `geometryCache` answers that from the session's own store, one request per neuron
 * already paid.
 */

import { ID_COLUMN_NAME } from '../../core/ids'
import type { ColumnsParam, EvalContext, InferContext } from '../../core/node'
import type { ColumnSchema, TableSchema } from '../../core/types'
import { columnNames, pickColumns } from '../../core/types'
import type { TableValue, Value } from '../../core/values'
import { isTableValue } from '../../core/values'
import { schemasFromType } from './datasetParam'
import { foldNodeColumns } from './networkOps'
import { joinTables, selectTable } from './tableOps'

/** One spelling of the param id, since the two nodes and both emitters read it. */
export const CARRY_PARAM_ID = 'carry'

/**
 * What the node calls one of the things it fetches, singular and plural.
 *
 * A table rather than `${noun}s`, which is how the first draft said "meshs" — the same reason
 * `plural` takes an explicit plural for the irregular cases (`ui/format.ts`), stated here because
 * this file cannot import the UI.
 */
type CarryNoun = 'skeleton' | 'mesh'
const PLURAL: Record<CarryNoun, string> = { skeleton: 'skeletons', mesh: 'meshes' }

/** The join every carry is: annotate the geometry's own rows, keep them all, keep their order. */
const CARRY_JOIN = {
  leftKey: ID_COLUMN_NAME,
  rightKey: ID_COLUMN_NAME,
  how: 'left',
} as const

/**
 * The control, shared by every node that fetches geometry for a neuron set.
 *
 * A factory taking only the **noun**, which is `warnAboveParam`' split and for the reason its own
 * comment gives: the shared clauses have to say the load-bearing half in the same words, and a
 * factory handed the whole sentence had the two adopters carrying 55 identical words each. What
 * varies between them is "skeleton" and "mesh".
 *
 * `excludeIds` keeps the id column out of the dropdown — it is the join key, so carrying it is a
 * no-op, and `ColumnParam.excludeIds`' own rule is that offering a choice nobody can use is the
 * thing to avoid. Declaring it is what replaced filtering the id out after resolution: that
 * version left `neuronId` in the picker, let somebody choose it, and discarded it in silence.
 */
export function carryParam(noun: CarryNoun): ColumnsParam {
  return {
    id: CARRY_PARAM_ID,
    kind: 'columns',
    label: 'Carry fields',
    from: 'neurons',
    excludeIds: true,
    // Empty is a legitimate state — carry nothing — and the commonest one, which is exactly
    // what `ColumnsParam.optional` is for: a picker nobody has touched raises no issue.
    optional: true,
    default: [],
    help:
      `Columns of the incoming neuron table to carry onto the ${PLURAL[noun]}, matched by ` +
      `neuronId. A ${noun} collection otherwise carries only what the fetch itself returns, so ` +
      'this is what ' +
      'puts a cell type, a hemisphere or an annotation within reach of Split Neurons, the 3D ' +
      'View’s colour picker and Download. A carried column replaces one of the same name.',
  }
}

/**
 * Which columns to take and the shape that results — one plan, read by both halves.
 *
 * The pair invariant 3 is about is separated here by a whole fetch: `inferOutputs` promises the
 * widened attribute table at edit time and `evaluate` builds it once the geometry lands, so a
 * disagreement surfaces only after a Run, as a column picker that empties. Sharing the plan is
 * what makes them agree by construction rather than by two functions happening to.
 *
 * `pickColumns`, not `selectSchema`: the latter is documented as "nothing chosen means
 * everything — the Select node's own rule", which is the opposite of what this wants, and the
 * first draft was saved from handing `joinSchema` the entire neuron schema only by the accident
 * of `neuronId` being in every pick list.
 */
function carryPlan(
  morphology: TableSchema,
  neurons: TableSchema,
  carry: readonly string[],
): { taken: ColumnSchema[]; kept: string[]; schema: TableSchema } {
  const taken = pickColumns(neurons, carry.filter(named))?.columns ?? []
  const names = new Set(taken.map((c) => c.name))
  return {
    taken,
    // The geometry's own columns minus the ones about to be written over them — which is how the
    // carried value wins the name. The id always survives: it is the join key.
    kept: columnNames(morphology).filter((n) => n === ID_COLUMN_NAME || !names.has(n)),
    schema: foldNodeColumns(morphology, taken),
  }
}

/** The id is the key rather than a carried column, and `joinTables` drops the right's copy. */
function named(name: string): boolean {
  return name !== ID_COLUMN_NAME
}

/**
 * What the geometry's attribute table looks like once these columns are carried onto it.
 *
 * The schema half. Either schema unknown, or nothing to carry, hands the morphology schema back
 * **by identity** — this runs on every graph mutation, and an unresolved dataset publishing no
 * schema must not be answered with a stand-in a downstream picker would then be configured
 * against.
 */
export function carriedSchema(
  morphology: TableSchema | undefined,
  neurons: TableSchema | undefined,
  carry: readonly string[],
): TableSchema | undefined {
  if (!morphology || !neurons || carry.length === 0) return morphology
  const plan = carryPlan(morphology, neurons, carry)
  return plan.taken.length === 0 ? morphology : plan.schema
}

/**
 * The same geometry with those columns carried onto its attribute table.
 *
 * The value half, and generic in the collection so a caller handing skeletons gets skeletons
 * back: one field changes, and every source's kind, items, bounds and frame come through
 * untouched. Points are accepted by the type — the attribute table is the only thing read —
 * though no node offers the control on a synapse cloud, whose rows are connectors rather than
 * neurons.
 *
 * Silently correct when there is nothing to do, which is what lets `evaluate` and the streaming
 * `onPartial` call it on the same line: no columns, no neuron table, or a table with none of the
 * named columns all hand the value straight back. There is deliberately **no error for a column
 * that has gone**: `resolveColumns` already drops a stored name the schema no longer offers and
 * `validateColumnParams` reports it on the card as `Missing column(s)` before anything runs. A
 * `ctx.warn` beside that was written first and was dead code twice over — unreachable, since
 * `ctx.columns` had already dropped the name, and a second spelling of a message the framework
 * owns.
 */
export function carriedGeometry<V extends { attributes: TableValue }>(
  value: V,
  neurons: Value | undefined,
  carry: readonly string[],
): V {
  if (!isTableValue(neurons) || carry.length === 0) return value
  const plan = carryPlan(value.attributes.schema, neurons.schema, carry)
  if (plan.taken.length === 0) return value

  const joined = joinTables(
    selectTable(value.attributes, plan.kept),
    selectTable(neurons, [ID_COLUMN_NAME, ...plan.taken.map((c) => c.name)]),
    CARRY_JOIN,
  )
  // Back into the plan's order, which is `foldNodeColumns`': an overridden column keeps the slot
  // it had rather than moving to the end, where every downstream table and CSV would show it.
  return { ...value, attributes: selectTable(joined, columnNames(plan.schema)) }
}

/**
 * The schema half, from a node's `InferContext`.
 *
 * A ctx-taking pair beside the pure functions, because each adopter was otherwise copying the
 * same three-argument expression and threading the same two values through three call sites —
 * `evaluate`, `onPartial` and the return. `importParams.ts` takes an `InferContext` for the same
 * reason. The pure functions stay exported for the tests, which is where the two halves are
 * checked against each other.
 */
export function carriedMorphology(ctx: InferContext): TableSchema | undefined {
  return carriedSchema(
    schemasFromType(ctx.inputs.dataset).morphology,
    ctx.schema('neurons'),
    ctx.columns(CARRY_PARAM_ID),
  )
}

/**
 * The value half, bound to a node's inputs once.
 *
 * Resolved before the fetch rather than per publish: `onPartial` fires every 250 ms for the life
 * of a long fetch, and re-reading the param and re-resolving the port on each one is work whose
 * answer cannot have changed. What it does *not* hoist is the join's own right-side index, which
 * `joinTables` rebuilds per call — that would need a prepared-index argument on a shared,
 * heavily-documented function, and it is a percent or so of a partial whose cost is dominated by
 * the source's own per-publish `boundsOf`/`cableLength` walk over every vertex delivered so far.
 */
export function carrying(
  ctx: EvalContext,
): <V extends { attributes: TableValue }>(value: V) => V {
  const carry = ctx.columns(CARRY_PARAM_ID)
  const neurons = ctx.input('neurons')
  return (value) => carriedGeometry(value, neurons, carry)
}
