/**
 * Graph metrics: the hand-worked cases, and the agreement with networkx.
 *
 * Two layers, and both are needed. The small graphs pin the decisions this module makes *for*
 * itself — a self-loop counts towards degree and nothing else, clustering is null rather than
 * zero on a leaf, the metric columns are written over the ones a network already carried —
 * which no external tool would ever confirm because they are choices rather than definitions.
 * The fixture pins the parts that are definitions: the values networkx gives for the same graph,
 * generated by `scripts/probe-network-metrics.py` and checked in, so the comparison runs on a
 * machine with no Python.
 *
 * The fixture is where a "simplification" gets caught. Every one of those numbers has a
 * plausible variant one line away — assortativity over excess degree rather than degree,
 * transitivity averaged per node rather than summed, clustering counting a reciprocal pair
 * twice — and each variant produces a column that looks entirely reasonable and is not the
 * number anybody else's tool would print.
 */

import { describe, expect, it } from 'vitest'

import { column, tableSchema } from '../../core/types'
import type { NetworkValue } from '../../core/values'
import { getColumn, tableFromRows } from '../../core/values'
import {
  DEFAULT_HISTOGRAM_CHOICE,
  METRIC_COLUMNS,
  coreness,
  countTriangles,
  degreeAssortativity,
  histogramChoices,
  indexNetwork,
  metricNodeSchema,
  networkMetrics,
  networkSummarySchema,
  nodeStatsSchema,
  parseHistogramChoice,
  projectUndirected,
  triangleWork,
} from './networkMetrics'
import { networkxColumn, networkxFixture, networkxValue } from './__fixtures__/networkx'

const NODE_SCHEMA = tableSchema(column('id', 'str'))
const EDGE_SCHEMA = tableSchema(
  column('source', 'str'),
  column('target', 'str'),
  column('weight', 'f64'),
)

function network(
  ids: string[],
  links: Array<[string, string, number?]>,
  directed = true,
): NetworkValue {
  return {
    kind: 'network',
    directed,
    nodes: tableFromRows(
      NODE_SCHEMA,
      ids.map((id) => ({ id })),
    ),
    edges: tableFromRows(
      EDGE_SCHEMA,
      links.map(([source, target, weight]) => ({ source, target, weight: weight ?? 1 })),
    ),
  }
}

/** One row of the summary as a plain object — it is always exactly one row. */
function summaryOf(net: NetworkValue): Record<string, unknown> {
  const table = networkMetrics(net).summary
  const row: Record<string, unknown> = {}
  for (const col of table.schema.columns) row[col.name] = table.data[col.name]![0]
  return row
}

function statsColumn(net: NetworkValue, name: string): unknown[] {
  return getColumn(networkMetrics(net).nodeStats, name)
}

describe('the undirected projection', () => {
  it('folds a reciprocal pair into one neighbour relationship', () => {
    const p = projectUndirected(
      indexNetwork(
        network(
          ['a', 'b'],
          [
            ['a', 'b'],
            ['b', 'a'],
          ],
        ),
      ),
    )
    expect(p.neighbour.length / 2).toBe(1)
    expect([...p.neighbour]).toEqual([1, 0])
    // Both directions survive as *directed* pairs, which is what reciprocity is counted over.
    expect(p.ordered.size).toBe(2)
  })

  it('drops self-loops, which cannot close a triangle', () => {
    const p = projectUndirected(
      indexNetwork(
        network(
          ['a', 'b'],
          [
            ['a', 'a'],
            ['a', 'b'],
          ],
        ),
      ),
    )
    expect(p.neighbour.length / 2).toBe(1)
    expect(p.ordered.size).toBe(1)
  })

  it('counts each triangle once and credits all three corners', () => {
    const triangle = network(
      ['a', 'b', 'c'],
      [
        ['a', 'b'],
        ['b', 'c'],
        ['c', 'a'],
      ],
    )
    const { perNode, total } = countTriangles(projectUndirected(indexNetwork(triangle)))
    expect(total).toBe(1)
    expect([...perNode]).toEqual([1, 1, 1])
  })

  it('measures the triangle count`s cost before running it', () => {
    // Σ over pairs (u, v), u < v, of d(v). On a triangle every node has degree 2 and there are
    // three forward pairs, so the walk is six steps — the number the warn threshold compares.
    const p = projectUndirected(
      indexNetwork(
        network(
          ['a', 'b', 'c'],
          [
            ['a', 'b'],
            ['b', 'c'],
            ['c', 'a'],
          ],
        ),
      ),
    )
    expect(triangleWork(p)).toBe(6)
  })

  it('peels a complete graph to its k-core', () => {
    const k4 = network(
      ['a', 'b', 'c', 'd'],
      [
        ['a', 'b'],
        ['a', 'c'],
        ['a', 'd'],
        ['b', 'c'],
        ['b', 'd'],
        ['c', 'd'],
      ],
    )
    expect([...coreness(projectUndirected(indexNetwork(k4)))]).toEqual([3, 3, 3, 3])
  })

  it('scores a star as perfectly disassortative', () => {
    const star = network(
      ['c', 'x', 'y', 'z'],
      [
        ['c', 'x'],
        ['c', 'y'],
        ['c', 'z'],
      ],
    )
    expect(degreeAssortativity(projectUndirected(indexNetwork(star)))).toBeCloseTo(-1, 12)
  })

  it('has no assortativity to report on a regular graph', () => {
    // Every link has identical ends, so the correlation is 0/0. Null says the question does not
    // apply; zero would say "no preference", which is a different and wrong claim.
    const ring = network(
      ['a', 'b', 'c'],
      [
        ['a', 'b'],
        ['b', 'c'],
        ['c', 'a'],
      ],
    )
    expect(degreeAssortativity(projectUndirected(indexNetwork(ring)))).toBeNull()
  })
})

describe('self-loops and dangling links', () => {
  it('counts a self-loop in both degrees and in nothing else', () => {
    const net = network(
      ['a', 'b'],
      [
        ['a', 'a', 5],
        ['a', 'b', 1],
      ],
    )
    const stats = networkMetrics(net).nodeStats
    expect(getColumn(stats, 'degreeOut')[0]).toBe(2)
    expect(getColumn(stats, 'degreeIn')[0]).toBe(1)
    expect(getColumn(stats, 'weightOut')[0]).toBe(6)

    const row = summaryOf(net)
    expect(row['selfLoops']).toBe(1)
    // One node pair among two nodes: density is 1/2 and not 2/2, which is what counting the
    // loop would give — a density above 1 is not a large number, it is a wrong one.
    expect(row['density']).toBe(0.5)
  })

  it('drops a link naming a node the network does not hold', () => {
    const net = network(
      ['a', 'b'],
      [
        ['a', 'b'],
        ['a', 'ghost'],
      ],
    )
    expect(indexNetwork(net).dangling).toBe(1)
    expect(summaryOf(net)['links']).toBe(1)
  })

  it('carries the cost and the drop count through a memo hit, so evaluate can always warn', () => {
    /*
     * The regression this replaces. The two warnings used to be raised *inside* the memoised
     * function, which looked equivalent and was not: the card calls it too — from the node's
     * *input*, so that the two calls share one triangle count — and it passes no warner. On the
     * ordinary chain the card therefore primed the memo first and `evaluate` got a hit and
     * warned about nothing. Both numbers ride on the result now, so a hit carries them.
     */
    const net = network(
      ['a', 'b', 'c'],
      [
        ['a', 'b'],
        ['b', 'c'],
        ['c', 'a'],
        ['a', 'ghost'],
      ],
    )
    const card = networkMetrics(net)
    const evaluated = networkMetrics(net)
    expect(evaluated).toBe(card)
    expect(evaluated.dangling).toBe(1)
    expect(evaluated.triangleWork).toBeGreaterThan(0)
  })

  it('hands the dropped count to the caller rather than warning from in here', () => {
    /*
     * The library is memoised and the *card* calls it too, from the node's input — so a warning
     * raised in here goes to whichever caller arrived first, which on the ordinary chain is the
     * card, with a silent warner. `dangling` comes back on the result and `evaluate` warns from
     * it; `nodes/output/networkMetrics.test.ts` is where the message itself is pinned.
     */
    expect(networkMetrics(network(['a', 'b'], [['a', 'ghost']])).dangling).toBe(1)
  })
})

describe('the summary row', () => {
  it('reports reciprocity over unique directed pairs, and nothing on an undirected graph', () => {
    const directed = network(
      ['a', 'b', 'c'],
      [
        ['a', 'b'],
        ['b', 'a'],
        ['a', 'c'],
      ],
    )
    expect(summaryOf(directed)['reciprocity']).toBeCloseTo(2 / 3, 12)

    const undirected = network(
      ['a', 'b', 'c'],
      [
        ['a', 'b'],
        ['a', 'c'],
      ],
      false,
    )
    expect(summaryOf(undirected)['reciprocity']).toBeNull()
  })

  it('counts parallel links without letting them inflate density', () => {
    const net = network(
      ['a', 'b'],
      [
        ['a', 'b'],
        ['a', 'b'],
        ['a', 'b'],
      ],
    )
    const row = summaryOf(net)
    expect(row['links']).toBe(3)
    expect(row['parallelLinks']).toBe(2)
    expect(row['density']).toBe(0.5)
  })

  it('averages clustering over the nodes that have one', () => {
    // Two leaves on one edge: neither has a pair of neighbours, so neither has a clustering
    // coefficient. Reporting them as zero would make `meanClustering` a count of the leaves.
    const net = network(['a', 'b'], [['a', 'b']])
    expect(statsColumn(net, 'clustering')).toEqual([null, null])
    expect(summaryOf(net)['meanClustering']).toBeNull()
  })

  it('numbers components largest-first and carries each node`s size', () => {
    const net = network(
      ['a', 'b', 'c', 'lonely'],
      [
        ['a', 'b'],
        ['b', 'c'],
      ],
    )
    expect(statsColumn(net, 'component')).toEqual([1, 1, 1, 2])
    expect(statsColumn(net, 'componentSize')).toEqual([3, 3, 3, 1])
    const row = summaryOf(net)
    expect(row['components']).toBe(2)
    expect(row['largestComponent']).toBe(3)
    expect(row['isolated']).toBe(1)
  })

  it('is exactly one row, whatever the graph', () => {
    expect(networkMetrics(network([], [])).summary.length).toBe(1)
    expect(networkMetrics(network(['a'], [])).summary.length).toBe(1)
  })
})

describe('the two halves agree', () => {
  it('writes over a metric column the node table already had', () => {
    const schema = tableSchema(
      column('id', 'str'),
      column('degreeIn', 'i64'),
      column('type', 'str'),
    )
    const net: NetworkValue = {
      kind: 'network',
      directed: true,
      nodes: tableFromRows(schema, [
        { id: 'a', degreeIn: 99, type: 'LC4' },
        { id: 'b', degreeIn: 99, type: 'LC6' },
      ]),
      edges: tableFromRows(EDGE_SCHEMA, [{ source: 'a', target: 'b', weight: 1 }]),
    }
    const out = networkMetrics(net).network
    expect(out.nodes.schema.columns.filter((c) => c.name === 'degreeIn')).toHaveLength(1)
    expect(getColumn(out.nodes, 'degreeIn')).toEqual([0, 1])
    // Everything else survives, in place: a column that moves to the end on every run is a
    // table whose columns reorder when nothing about it changed.
    expect(out.nodes.schema.columns.map((c) => c.name).slice(0, 3)).toEqual([
      'id',
      'degreeIn',
      'type',
    ])
    expect(getColumn(out.nodes, 'type')).toEqual(['LC4', 'LC6'])
  })

  it('promises exactly the columns it produces', () => {
    const net = network(['a', 'b'], [['a', 'b']])
    const result = networkMetrics(net)
    expect(result.nodeStats.schema).toEqual(nodeStatsSchema())
    expect(result.summary.schema).toEqual(networkSummarySchema())
    expect(result.network.nodes.schema).toEqual(metricNodeSchema(net.nodes.schema))
    for (const name of METRIC_COLUMNS) {
      expect(result.network.nodes.data[name]).toBeDefined()
      expect(result.nodeStats.data[name]).toBeDefined()
    }
  })
})

// ---------------------------------------------------------------------------
// Against networkx
// ---------------------------------------------------------------------------

function fixtureNetwork(directed: boolean): NetworkValue {
  return network(
    networkxFixture.nodes,
    networkxFixture.links.map(([a, b, w]) => [a, b, w] as [string, string, number]),
    directed,
  )
}

describe('agreement with networkx', () => {
  it('matches its density and reciprocity', () => {
    const row = summaryOf(fixtureNetwork(true))
    expect(row['density']).toBeCloseTo(networkxValue('directed', 'density'), 12)
    expect(row['reciprocity']).toBeCloseTo(networkxValue('directed', 'reciprocity'), 12)
    expect(summaryOf(fixtureNetwork(false))['density']).toBeCloseTo(
      networkxValue('undirected', 'density'),
      12,
    )
  })

  it('matches its clustering, node for node, where the node has one', () => {
    const net = fixtureNetwork(true)
    const ours = statsColumn(net, 'clustering')
    const theirs = networkxColumn('undirected', 'clustering')
    const projection = projectUndirected(indexNetwork(net))
    let compared = 0
    ours.forEach((value, row) => {
      const degree = projection.offset[row + 1]! - projection.offset[row]!
      if (degree < 2) {
        // Where networkx says 0, this says null — the one documented departure, and the
        // reason `meanClustering` is not compared against `average_clustering`.
        expect(value).toBeNull()
        return
      }
      expect(value as number).toBeCloseTo(theirs[row]!, 12)
      compared++
    })
    expect(compared).toBeGreaterThan(40)
  })

  it('matches its transitivity, assortativity and k-core', () => {
    const net = fixtureNetwork(true)
    const row = summaryOf(net)
    expect(row['transitivity']).toBeCloseTo(networkxValue('undirected', 'transitivity'), 12)
    expect(row['assortativity']).toBeCloseTo(networkxValue('undirected', 'assortativity'), 12)
    expect(statsColumn(net, 'coreness')).toEqual(networkxColumn('undirected', 'coreness'))
  })

  it('matches its component count and largest component', () => {
    const row = summaryOf(fixtureNetwork(true))
    expect(row['components']).toBe(networkxValue('undirected', 'components'))
    expect(row['largestComponent']).toBe(networkxValue('undirected', 'largestComponent'))
  })
})

describe('the histogram picker’s vocabulary', () => {
  const NODES = tableSchema(column('id', 'str'), column('cellType', 'str'))
  const EDGES = tableSchema(column('source', 'str'), column('weight', 'f64'))

  it('offers the metrics before the network has any, and always the component sizes', () => {
    // Called with nothing wired, which is the state the node`s param is asked in: the list has
    // to hold the default or the picker opens on a value it does not offer.
    const values = histogramChoices(undefined, undefined).map((o) => o.value)
    expect(values).toContain(DEFAULT_HISTOGRAM_CHOICE)
    expect(values).toContain('components:size')
  })

  it('prefixes the link columns, because `weight` is a word both tables use', () => {
    const options = histogramChoices(NODES, EDGES)
    expect(options).toContainEqual({ value: 'links:weight', label: 'link weight' })
    // And offers no string column on either side — nothing here bins a cell type.
    expect(options.map((o) => o.value)).not.toContain('nodes:cellType')
    expect(options.map((o) => o.value)).not.toContain('links:source')
  })

  it('reads a stored pair back, and keeps a column the network does not have', () => {
    expect(parseHistogramChoice('links:weight')).toEqual({ source: 'links', column: 'weight' })
    // The rule a column picker follows: a schema without a column is very often a schema that
    // has not arrived, so this comes back as written rather than substituted.
    expect(parseHistogramChoice('nodes:betweenness')).toEqual({
      source: 'nodes',
      column: 'betweenness',
    })
  })

  it('falls back only on something that is not a pair at all', () => {
    for (const stored of ['', 'degree', 'nowhere:degree', 'nodes:', 42, undefined]) {
      expect(parseHistogramChoice(stored)).toEqual({ source: 'nodes', column: 'degree' })
    }
  })
})
