/**
 * Node pack registration.
 *
 * Importing this module registers every built-in node. The editor imports it once at
 * startup; tests import it when they need the real node set. Keep the imports explicit
 * (no glob) so the bundle is analysable and registration order is deterministic.
 */

import './annotation/note'
import './dataset'
import './annotation'
import './dataset/description'
import './dataset/ngsource'
import './query/dataset'
import './query/explore'
import './query/findNeurons'
import './query/idsFromLabel'
import './query/inputIds'
import './query/roiCounts'
import './query/roiCompleteness'
import './query/roiMeshes'
import './query/uploadMesh'
import './query/morphology'
// The node packs. Every pack's nodes register here, at this one position, rather than where each
// module used to be imported — so a moved node lists later in `listableNodeDefs()` than it did.
// Every surface a reader sees sorts by label, which is why that shows nowhere else.
import '../packs'

import './table/filter'
import './table/sort'
import './table/sample'
import './table/groupBy'
import './table/combine'
import './table/dedupe'
import './table/select'
import './table/rename'
import './table/editTable'
import './table/join'
import './table/relabel'
import './table/qualifyIds'
import './table/stack'
import './table/pivot'
import './table/unpivot'
import './table/normalize'
import './table/reduceMatrix'
import './table/upload'
import './table/fromUrl'
import './transform/selectOne'
import './flow/forEach'
import './flow/collect'
import './transform/mirror'
import './transform/xform'
import './transform/splitNeurons'
import './transform/selectNeurons'
import './transform/pointsInVolumes'
import './transform/attachAttributes'
import './transform/stackNeurons'
import './transform/landmarkTransform'
import './transform/cleanSkeletons'
import './transform/cleanMeshes'
import './transform/labelsToNeurons'
import './analysis/buildNetwork'
import './analysis/distance'
import './analysis/nblast'
import './analysis/nblastKnn'
import './analysis/nblastMatches'
import './analysis/filterNetwork'
import './analysis/networkCentrality'
import './analysis/similarity'
import './analysis/linkage'
import './analysis/cutTree'
import './analysis/embed'

import './output/table'
import './output/describe'
import './output/networkMetrics'
import './output/heatmap'
import './output/dendrogram'
import './output/barChart'
import './output/histogram'
import './output/pie'
import './output/distribution'
import './output/scatter'
import './output/rank'
import './output/sankey'
import './output/network'
import './output/flowChart'
import './output/viewer3d'
import './output/neuroglancer'
import './output/profile'
import './output/topology'
import './output/neuronbridge'
import './output/datasetSummary'
import './output/rois'
import './output/download'
import './output/copyIds'
