/**
 * The networkx fixture, and the two readers both metric tests want.
 *
 * `networkx.json` is generated by `scripts/probe-network-metrics.py` — one seeded graph and
 * networkx's answer for every metric `networkMetrics.ts` and `networkCentrality.ts` also compute.
 * Beside the data rather than in a test file because both suites read it and neither owns it, and
 * because a second copy of "which file, what shape, how a per-node column is put back into row
 * order" is a second thing to keep in step with a generator that neither test runs.
 *
 * Deliberately *not* a home for the `network()` builder those tests also share: a per-file graph
 * factory is the convention here (`networkOps.test.ts`, `networkLayout.test.ts` and
 * `networkDraw.test.ts` each have their own), and a shared one would fight it.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'

export interface NetworkxFixture {
  nodes: string[]
  links: Array<[string, string, number]>
  directed: Record<string, number | Record<string, number>>
  undirected: Record<string, number | Record<string, number>>
}

export const networkxFixture: NetworkxFixture = JSON.parse(
  readFileSync(join(__dirname, 'networkx.json'), 'utf8'),
) as NetworkxFixture

/** A per-node column from the fixture, in the fixture's own node order. */
export function networkxColumn(part: 'directed' | 'undirected', metric: string): number[] {
  const byId = networkxFixture[part][metric] as Record<string, number>
  return networkxFixture.nodes.map((id) => byId[id]!)
}

/** A graph-level number from the fixture. */
export function networkxValue(part: 'directed' | 'undirected', metric: string): number {
  return networkxFixture[part][metric] as number
}
