/**
 * The generator half of the Zoo contract: turn a deposited workflow into an index entry, and
 * refuse the ones that would arrive broken.
 *
 * Runs in Node, from `scripts/zoo-index.ts`, which is what `navis-org/coda-zoo`'s CI invokes.
 * It lives here rather than in the zoo repository for one reason: **every interesting check
 * needs Coda's registry**. Whether `out.network` still exists, whether a param survived a
 * rename, whether the declared `requires` matches the dataset nodes actually in the graph —
 * none of that is answerable by a script that only sees JSON. A validator that cannot see the
 * registry can only check that the braces balance, and the failure it misses is precisely the
 * one this feature has: a workflow deposited last year that opens today with a node silently
 * dropped out of the middle of it.
 *
 * The cost is that the zoo's CI checks out Coda and installs it. That is a minute on a pull
 * request, and it buys the property that **the index cannot be generated by a Coda that does
 * not agree with it** — regenerate on a schedule and registry drift surfaces as a red build in
 * the zoo instead of a blank card in somebody's browser.
 *
 * Nothing here fetches. It is handed text and hands back an entry plus a list of problems; the
 * script owns the filesystem and the exit code.
 */

import type { CodaGraph } from '../../core/graph'
import { deserializeGraph } from '../../core/graph'
import { inferGraph } from '../../core/inference'
import { getNodeDef } from '../../core/registry'
import {
  CUSTOM_DATASET_NODES,
  DATASET_NODE_PREFIX,
  familyForNodeType,
} from '../../nodes/lib/datasetFamilies'
import type { ZooEntry, ZooLayout } from './format'
import { SLUG_PATTERN, authorList, isRepoPath, str, strings } from './format'

/**
 * A problem with a deposited workflow.
 *
 * Two levels, and the split is what a pull request does with them: an `error` fails the build
 * and the entry does not enter the index, a `warning` is printed and the entry ships. The line
 * between them is whether a *reader* would be misled. A missing tag is nobody's problem; a
 * graph carrying a node type this build has never heard of is a card that opens onto a hole.
 */
export interface ZooProblem {
  level: 'error' | 'warning'
  message: string
}

/** What a contributor writes in `meta.json`. Everything else on a `ZooEntry` is derived. */
export interface ZooMeta {
  name?: unknown
  summary?: unknown
  tags?: unknown
  authors?: unknown
  requires?: unknown
}

/**
 * The graph's minimap, as `ZooLayout` describes it.
 *
 * A node's *size* is deliberately not carried. Most graphs never set one — `size` is absent
 * until somebody drags a corner — so the generator would be emitting a number it had to invent
 * for almost every node, and the renderer has the registry and can ask for the real default. A
 * digest should carry what only the generator knows.
 */
export function layoutDigest(graph: CodaGraph): ZooLayout {
  const index = new Map<string, number>()
  const nodes: ZooLayout['nodes'] = graph.nodes.map((node, i) => {
    index.set(node.id, i)
    return [Math.round(node.position.x), Math.round(node.position.y), node.type]
  })

  const edges: ZooLayout['edges'] = []
  const seen = new Set<string>()
  for (const edge of graph.edges) {
    const from = index.get(edge.source)
    const to = index.get(edge.target)
    if (from === undefined || to === undefined || from === to) continue
    // Two wires between the same pair draw one line at this scale, and the duplicate is only
    // extra bytes in an index that every visitor downloads.
    const key = `${from}>${to}`
    if (seen.has(key)) continue
    seen.add(key)
    edges.push([from, to])
  }

  return { nodes, edges }
}

/**
 * The registered sources a graph's dataset nodes reach for, sorted and deduplicated.
 *
 * Both kinds of dataset node count: a family node (`dataset.hemibrain`) names its source in the
 * family table, and a custom node (`dataset.neuprint`) names the *default* instance for its
 * backend. A custom node routinely points somewhere else at run time — that is what it is for —
 * so what this answers is "which kind of credential does opening this ask for", which is the
 * question the browser's card is putting to the reader.
 */
export function graphRequires(graph: CodaGraph): string[] {
  const sources = new Set<string>()
  for (const node of graph.nodes) {
    if (!node.type.startsWith(DATASET_NODE_PREFIX)) continue
    const family = familyForNodeType(node.type)
    if (family) {
      sources.add(family.sourceId)
      continue
    }
    const custom = CUSTOM_DATASET_NODES.find((entry) => entry.type === node.type)
    if (custom) sources.add(custom.sourceId)
  }
  return [...sources].sort()
}

/**
 * Every problem a graph has, at the same bar the bundled examples are held to.
 *
 * `examples.test.ts` asserts each shipped example is free of inference errors *and* warnings,
 * and a deposited workflow is held to that same line — a zoo entry is documentation as much as
 * the examples are, and "it mostly works" is not a thing a reader can evaluate from a card.
 *
 * The param check is the one that is not in `examples.test.ts`, and it is the drift detector.
 * `deserializeGraph` keeps params verbatim: a param a node no longer declares survives the load
 * silently, does nothing, and leaves a workflow that looks configured and is not. Reported as a
 * warning rather than an error because the usual cause is a rename with a working default on
 * the other side, and losing a contributor's workflow over that would be worse than saying so.
 */
export function graphProblems(graphText: string): {
  graph?: CodaGraph
  problems: ZooProblem[]
} {
  const problems: ZooProblem[] = []

  let loaded
  try {
    loaded = deserializeGraph(graphText)
  } catch (err) {
    return { problems: [{ level: 'error', message: (err as Error).message }] }
  }

  // A load warning is an error here. In the app it means "we saved what we could of your file";
  // in a repository it means the entry as committed is not the entry that will open.
  for (const warning of loaded.warnings) problems.push({ level: 'error', message: warning })

  const graph = loaded.graph
  if (graph.nodes.length === 0) {
    problems.push({ level: 'error', message: 'the graph has no nodes' })
  }

  for (const node of graph.nodes) {
    const def = getNodeDef(node.type)
    if (!def) continue // already reported as a dropped node type above
    const declared = new Set((def.params ?? []).map((param) => param.id))
    for (const key of Object.keys(node.params ?? {})) {
      if (declared.has(key)) continue
      problems.push({
        level: 'warning',
        message: `${node.id} (${node.type}) carries param "${key}", which the node no longer declares`,
      })
    }
  }

  const inference = inferGraph(graph)
  for (const [nodeId, node] of Object.entries(inference.nodes)) {
    for (const issue of node.issues) {
      problems.push({
        level: issue.severity === 'error' ? 'error' : 'warning',
        message: `${nodeId}: ${issue.message}`,
      })
    }
  }
  for (const nodeId of inference.cyclic) {
    problems.push({ level: 'error', message: `${nodeId} is part of a cycle` })
  }

  return { graph, problems }
}

export interface BuildEntryInput {
  slug: string
  /** Parsed `meta.json`. */
  meta: ZooMeta
  /** The contents of `graph.coda.json`. */
  graphText: string
  /** Repository-relative path to the graph. */
  graphPath: string
  /** Repository-relative path to the README, where the entry has one. */
  readmePath?: string
  /** ISO 8601 of the last commit touching the entry. The script reads it from git. */
  updatedAt: string
}

const SUMMARY_MAX = 140

/**
 * One validated index entry, or the reasons there isn't one.
 *
 * `requires` is **compared** rather than derived. Deriving it would always be right and would
 * teach a contributor nothing; comparing turns "I did not realise this needed a CAVE token"
 * into a failed check with the answer in it, at the moment somebody is still holding the
 * workflow in their head. It is the one field where the redundancy is the feature.
 */
export function buildEntry(input: BuildEntryInput): {
  entry?: ZooEntry
  problems: ZooProblem[]
} {
  const problems: ZooProblem[] = []
  const { slug } = input

  if (!SLUG_PATTERN.test(slug)) {
    problems.push({ level: 'error', message: `directory name "${slug}" must be kebab-case` })
  }
  if (!isRepoPath(input.graphPath)) {
    problems.push({
      level: 'error',
      message: `graph path "${input.graphPath}" is not repo-relative`,
    })
  }

  const name = str(input.meta.name)
  if (!name) problems.push({ level: 'error', message: 'meta.json has no "name"' })

  const summary = str(input.meta.summary)
  if (!summary) {
    problems.push({ level: 'error', message: 'meta.json has no "summary"' })
  } else if (summary.length > SUMMARY_MAX) {
    // A card gives the summary one line. A paragraph pasted here does not wrap into more room,
    // it is simply cut off mid-sentence — so it is refused where the author can still fix it,
    // and the README is where the long version belongs.
    problems.push({
      level: 'error',
      message: `summary is ${summary.length} characters; the card shows one line, so keep it under ${SUMMARY_MAX}. Put the long version in README.md.`,
    })
  }

  const tags = strings(input.meta.tags).map((tag) => tag.toLowerCase())
  if (tags.length === 0) {
    problems.push({
      level: 'warning',
      message: 'no tags: the entry will only be found by name',
    })
  }

  const people = authorList(input.meta.authors)
  if (people.length === 0) {
    problems.push({ level: 'warning', message: 'no authors listed' })
  }

  const { graph, problems: graphIssues } = graphProblems(input.graphText)
  problems.push(...graphIssues)
  if (!graph) return { problems }

  const actual = graphRequires(graph)
  const declared = [...new Set(strings(input.meta.requires))].sort()
  const missing = actual.filter((source) => !declared.includes(source))
  const extra = declared.filter((source) => !actual.includes(source))
  if (missing.length) {
    problems.push({
      level: 'error',
      message: `meta.json "requires" is missing ${missing.join(', ')} — the graph has dataset nodes for ${actual.join(', ') || 'nothing'}`,
    })
  }
  if (extra.length) {
    problems.push({
      level: 'error',
      message: `meta.json "requires" lists ${extra.join(', ')}, which no dataset node in the graph uses`,
    })
  }

  if (problems.some((problem) => problem.level === 'error')) return { problems }

  return {
    entry: {
      slug,
      name: name!,
      summary: summary!,
      tags,
      authors: people,
      requires: actual,
      graph: input.graphPath,
      ...(input.readmePath ? { readme: input.readmePath } : {}),
      nodeCount: graph.nodes.length,
      layout: layoutDigest(graph),
      updatedAt: input.updatedAt,
    },
    problems,
  }
}
