#!/usr/bin/env python3
"""Regenerate the networkx fixture the graph-metric tests are pinned against.

`src/nodes/lib/networkMetrics.ts` and `networkCentrality.ts` claim, in several comments, that a
number quoted from Coda is the same number networkx would give — betweenness normalised the same
way, harmonic centrality defined in the same direction, degree assortativity over the same
projection. Those claims are the kind that stay true right up until somebody "simplifies" a
denominator, and nothing on screen would say so.

So they are checked rather than asserted. This script builds one seeded graph, asks networkx for
every metric the two modules also compute, and writes both the graph and the answers to
`src/nodes/lib/__fixtures__/networkx.json`. `networkMetrics.test.ts` and
`networkCentrality.test.ts` read that file and compare — which means the comparison runs in CI on
a machine with no Python at all, and this script only has to run again when the graph or the set
of metrics changes.

    python3 scripts/probe-network-metrics.py

Deliberately *not* wired into `pnpm test`: regenerating a golden as part of the run that checks it
is how a golden stops checking anything.

Two shapes are emitted, because several of these behave differently on each: a directed graph
with reciprocal pairs, and its undirected projection. Neither has self-loops — networkx's
`density` counts them and Coda's does not, and the disagreement there is a documented decision
rather than a bug, so it is covered by a hand-worked unit test instead of hidden inside a fixture
that would then encode the wrong answer.
"""

import json
import pathlib
import random

import networkx as nx

OUT = pathlib.Path(__file__).resolve().parents[1] / "src/nodes/lib/__fixtures__/networkx.json"

# Two components on purpose: a connectome network after any filter is mostly not connected, and
# every path metric here has a different answer for "cannot be reached" than for "far away".
NODES = 60
BRIDGE = 42  # everything below is one component, everything from here up is another


def build() -> nx.DiGraph:
    rand = random.Random(20260901)
    g = nx.DiGraph()
    for i in range(NODES):
        g.add_node(str(i))

    def link(a: int, b: int) -> None:
        if a == b:
            return
        # Weights spread over two orders of magnitude, as synapse counts are — a weighted path
        # metric tested on near-uniform weights is a metric tested on hops.
        g.add_edge(str(a), str(b), weight=float(rand.randint(1, 200)))

    # A connected backbone per component, then random chords over it.
    for i in range(1, BRIDGE):
        link(rand.randrange(0, i), i)
    for i in range(BRIDGE + 1, NODES - 2):
        link(rand.randrange(BRIDGE, i), i)
    for _ in range(180):
        a = rand.randrange(0, BRIDGE)
        b = rand.randrange(0, BRIDGE)
        link(a, b)
    for _ in range(40):
        a = rand.randrange(BRIDGE, NODES - 2)
        b = rand.randrange(BRIDGE, NODES - 2)
        link(a, b)
    # Reciprocal pairs, so `reciprocity` is not measuring zero, and two isolated nodes so
    # `isolated`, `components` and the null-clustering rule all have something to bite on.
    for a, b in [(1, 2), (3, 4), (5, 6), (44, 45)]:
        link(a, b)
        link(b, a)
    return g


def path_stats(g: nx.Graph) -> dict:
    """Mean and maximum shortest-path length over *reachable* ordered pairs.

    Coda's definition, which is not `average_shortest_path_length` — that one raises on a graph
    that is not connected, which every real one here is not.
    """
    total = 0.0
    pairs = 0
    longest = 0.0
    for _, lengths in nx.all_pairs_shortest_path_length(g):
        for target, d in lengths.items():
            del target
            if d == 0:
                continue
            total += d
            pairs += 1
            longest = max(longest, d)
    return {
        "meanPathLength": total / pairs if pairs else None,
        "diameter": longest,
        "reachable": pairs / (g.number_of_nodes() * (g.number_of_nodes() - 1)),
    }


def main() -> None:
    g = build()
    u = nx.Graph()
    u.add_nodes_from(g.nodes())
    for a, b, data in g.edges(data=True):
        # The undirected projection Coda takes: a reciprocal pair is one neighbour relationship
        # whose weight is the *sum* of the two directions. Summing rather than picking one is
        # what makes a weighted answer independent of whether parallel links were merged
        # upstream — see `buildAdjacency`'s note on the same decision.
        if u.has_edge(a, b):
            u[a][b]["weight"] += data["weight"]
        else:
            u.add_edge(a, b, weight=data["weight"])

    n = g.number_of_nodes()
    harmonic = nx.harmonic_centrality(g)
    components = list(nx.connected_components(u))

    fixture = {
        "note": "Generated by scripts/probe-network-metrics.py — do not edit by hand.",
        "networkx": nx.__version__,
        "nodes": list(g.nodes()),
        "links": [[a, b, data["weight"]] for a, b, data in g.edges(data=True)],
        "directed": {
            "density": nx.density(g),
            "reciprocity": nx.overall_reciprocity(g),
            "betweenness": nx.betweenness_centrality(g, normalized=True),
            # Coda divides by n - 1 so the column is comparable across graphs; networkx does not.
            "closeness": {k: v / (n - 1) for k, v in harmonic.items()},
            # Tighter than networkx's 1e-6 default, which stops about five decimal places short of
            # converged — close enough for a ranking and not close enough to pin an implementation
            # against. Coda iterates to 1e-10.
            "pagerank": nx.pagerank(g, alpha=0.85, weight="weight", tol=1e-12, max_iter=500),
            **path_stats(g),
        },
        "undirected": {
            "density": nx.density(u),
            "clustering": nx.clustering(u),
            "transitivity": nx.transitivity(u),
            "assortativity": nx.degree_assortativity_coefficient(u),
            "coreness": nx.core_number(u),
            "components": len(components),
            "largestComponent": max(len(c) for c in components),
            "eigenvector": nx.eigenvector_centrality(u, max_iter=1000, tol=1e-12, weight="weight"),
        },
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=1, sort_keys=True) + "\n")
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())}")
    print(f"  {n} nodes, {g.number_of_edges()} links, {len(components)} components")


if __name__ == "__main__":
    main()
