/**
 * `virtual:node-guide-data` — the node registry, read at build time.
 *
 * The node guide draws every card, socket and setting from the real `NodeDefinition`s, which
 * leaves the question of how a static page gets at them. Three routes, and only one survives:
 *
 *  - **Import the registry into the page.** Correct and unmaintainable in the other direction:
 *    measured at 660 kB (211 kB gzipped) plus elkjs and the Draco decoder, on a page whose whole
 *    point is that it costs 5 kB.
 *  - **Commit a generated JSON** with a golden test to catch staleness — the idiom
 *    `src/export/__fixtures__` already uses. Works, and pays for a file in the repo that has to
 *    be regenerated by hand and reviewed in every diff that touches a node.
 *  - **Load it at build time**, which is this. `ssrLoadModule` runs `src/nodeguide/data.ts` in
 *    Node, through Vite's own TypeScript pipeline, and the result is inlined as a virtual
 *    module. Nothing is committed, nothing can drift, and the page stays static.
 *
 * Measured at ~250 ms, once per build.
 *
 * ## Dev and build take different servers, and that is not an oversight
 *
 * In dev the running server is already there and `configureServer` hands it over, so the guide
 * picks up an edit to a node definition on reload like any other source change. A production
 * build has no server, so one is created for the length of the call and closed again.
 * `configFile: false` on that one is deliberate: loading this config from inside itself would
 * recurse, and nothing in `src/nodes` uses the `@` alias — checked, and the reason `data.ts`
 * imports by relative path.
 */

import type { Plugin, ViteDevServer } from 'vite'
import { createServer } from 'vite'

/*
 * Structurally typed here rather than imported from `src/nodeguide/data`.
 *
 * `tsconfig.node.json` covers the build tooling and `tsconfig.app.json` covers `src`; a
 * type-only import across that line pulls `src/core` into the tooling project's file list and
 * the build stops type-checking. Nothing here reads a field anyway — the value is loaded and
 * stringified — so the shape it needs is "an object".
 */
type GuideData = Record<string, unknown>

const VIRTUAL_ID = 'virtual:node-guide-data'
const RESOLVED_ID = '\0' + VIRTUAL_ID
const ENTRY = '/src/nodeguide/data.ts'

async function readRegistry(server: ViteDevServer | undefined): Promise<GuideData> {
  if (server) {
    const mod = (await server.ssrLoadModule(ENTRY)) as { guideData: () => GuideData }
    return mod.guideData()
  }
  const own = await createServer({
    configFile: false,
    logLevel: 'error',
    server: { middlewareMode: true, hmr: false, watch: null },
    optimizeDeps: { noDiscovery: true },
  })
  try {
    const mod = (await own.ssrLoadModule(ENTRY)) as { guideData: () => GuideData }
    return mod.guideData()
  } finally {
    await own.close()
  }
}

export function nodeGuideData(): Plugin {
  let server: ViteDevServer | undefined

  return {
    name: 'coda:node-guide-data',
    configureServer(devServer) {
      server = devServer
    },
    resolveId(id) {
      return id === VIRTUAL_ID ? RESOLVED_ID : undefined
    },
    async load(id) {
      if (id !== RESOLVED_ID) return undefined
      const data = await readRegistry(server)
      return `export default ${JSON.stringify(data)}`
    },
    /*
     * In dev, a change to any node definition has to invalidate the virtual module — otherwise
     * the guide keeps serving whatever the registry said when the page first loaded, which is
     * the one failure mode that would make this worse than a committed file.
     */
    handleHotUpdate(ctx) {
      if (!/\/src\/(nodes|core|examples)\//.test(ctx.file)) return
      const mod = ctx.server.moduleGraph.getModuleById(RESOLVED_ID)
      if (mod) ctx.server.moduleGraph.invalidateModule(mod)
    },
  }
}
