/**
 * `virtual:node-guide-data` — the node registry, read at build time — and the static index it
 * also feeds into `nodes.html`.
 *
 * The node guide draws every card, socket and setting from the real `NodeDefinition`s, which
 * leaves the question of how a static page gets at them. Three routes, and only one survives:
 *
 *  - **Import the registry into the page.** Correct and unmaintainable in the other direction:
 *    measured at 660 kB (211 kB gzipped) plus elkjs and the Draco decoder, on a page whose whole
 *    point is that it costs 5 kB.
 *  - **Commit a generated JSON** with a golden test to catch staleness — the idiom
 *    `src/export/__fixtures__` already uses. Works, and pays for a file in the repo that has to
 *    be regenerated by hand and reviewed in every diff that touches a node.
 *  - **Load it at build time**, which is this. `ssrLoadModule` runs `src/nodeguide/data.ts` in
 *    Node, through Vite's own TypeScript pipeline, and the result is inlined as a virtual
 *    module. Nothing is committed, nothing can drift, and the page stays static.
 *
 * Measured at ~250 ms, once per build.
 *
 * ## Two consumers, one server
 *
 * The virtual module is the page's; `src/nodeguide/appendix.ts` is the other, and it renders
 * every node's prose as static markup that `transformIndexHtml` splices into `nodes.html` in
 * place of `<!--@node-appendix-->`. That is here rather than in `vite/seo.ts` because it is the
 * same concern — the registry, read in Node during a build — and the alternative was a second
 * copy of the throwaway-server dance below. Which is also why the build's server is created
 * once and closed in `closeBundle` rather than per call: the two consumers then share one module
 * graph and the registry is evaluated once, not twice.
 *
 * ## Dev and build take different servers, and that is not an oversight
 *
 * In dev the running server is already there and `configureServer` hands it over, so the guide
 * picks up an edit to a node definition on reload like any other source change. A production
 * build has none, so one is created on first use and closed in `closeBundle`. `configFile: false`
 * on that one is deliberate: loading this config from inside itself would recurse, and nothing in
 * `src/nodes` uses the `@` alias — checked, and the reason `data.ts` imports by relative path.
 */

import type { Plugin, ViteDevServer } from 'vite'
import { createServer } from 'vite'

/*
 * Structurally typed here rather than imported from `src/nodeguide/data`.
 *
 * `tsconfig.node.json` covers the build tooling and `tsconfig.app.json` covers `src`; a
 * type-only import across that line pulls `src/core` into the tooling project's file list and
 * the build stops type-checking. Nothing here reads a field anyway — the value is loaded and
 * stringified — so the shape it needs is "an object".
 */
type GuideData = Record<string, unknown>

const VIRTUAL_ID = 'virtual:node-guide-data'
const RESOLVED_ID = '\0' + VIRTUAL_ID
const DATA_ENTRY = '/src/nodeguide/data.ts'
const APPENDIX_ENTRY = '/src/nodeguide/appendix.ts'

/** The marker `nodes.html` carries where the static index goes. */
const APPENDIX_SLOT = '<!--@node-appendix-->'

export function nodeGuideData(): Plugin {
  /** The dev server, when there is one. */
  let server: ViteDevServer | undefined
  /** The build's own, created on first use and closed in `closeBundle`. */
  let owned: ViteDevServer | undefined

  async function ssr<T>(entry: string): Promise<T> {
    if (server) return (await server.ssrLoadModule(entry)) as T
    owned ??= await createServer({
      configFile: false,
      logLevel: 'error',
      server: { middlewareMode: true, hmr: false, watch: null },
      optimizeDeps: { noDiscovery: true },
    })
    return (await owned.ssrLoadModule(entry)) as T
  }

  return {
    name: 'coda:node-guide-data',
    configureServer(devServer) {
      server = devServer
    },
    async closeBundle() {
      await owned?.close()
      owned = undefined
    },

    /**
     * The static index, spliced into `nodes.html`.
     *
     * Returns the html untouched when the marker is absent, which is every other entry — and is
     * also what makes removing the marker a way to turn this off without touching the plugin.
     */
    async transformIndexHtml(html) {
      if (!html.includes(APPENDIX_SLOT)) return
      const mod = await ssr<{ appendixHTML: () => string }>(APPENDIX_ENTRY)
      return html.replace(APPENDIX_SLOT, mod.appendixHTML())
    },
    resolveId(id) {
      return id === VIRTUAL_ID ? RESOLVED_ID : undefined
    },
    async load(id) {
      if (id !== RESOLVED_ID) return undefined
      const mod = await ssr<{ guideData: () => GuideData }>(DATA_ENTRY)
      return `export default ${JSON.stringify(mod.guideData())}`
    },
    /*
     * In dev, a change to any node definition has to invalidate the virtual module — otherwise
     * the guide keeps serving whatever the registry said when the page first loaded, which is
     * the one failure mode that would make this worse than a committed file.
     */
    handleHotUpdate(ctx) {
      if (!/\/src\/(nodes|core|examples|wizard)\//.test(ctx.file)) return
      const mod = ctx.server.moduleGraph.getModuleById(RESOLVED_ID)
      if (mod) ctx.server.moduleGraph.invalidateModule(mod)
    },
  }
}
