/**
 * Generated Python helpers for the Custom Dataset and the table files it reads.
 *
 * The counterpart of `caveHelpers.ts` for the parts a Custom Dataset is assembled from: a table
 * file read by columns and ids, a precomputed bucket's geometry, and the class standing in for
 * `CompositeSource` so a downstream cell has one object to ask. Each mirrors a piece of
 * `src/data/files`, `src/data/edges` or `src/data/custom`, and that pairing is the thing to keep
 * true. `pnpm probe:helpers` runs the Custom Dataset golden whole against files it writes.
 */

import { registerHelper } from './registry'

/**
 * An id column as exact text, or `<NA>` where a value is no id — `idText` in `core/ids.ts`, over a
 * column at once.
 *
 * Built on `coda_ids` rather than beside it, so the notebook has one cast: this adds only `idText`'s
 * refusals — a blank, a fractional float, and a float past 2^53, which is already a different
 * neuron and would be hidden by turning it into text. Vectorised because it meets whole tables,
 * and cast once per distinct value where they repeat — an edge list's ends, a synapse table's.
 */
registerHelper({
  name: 'coda_id_column',
  needs: ['coda_ids'],
  requires: [['pandas']],
  source: [
    'def coda_id_column(values):',
    '    """Convert an id column to exact text, with <NA> where a value is not a valid id.',
    '',
    "    Mirrors `idText` in Coda's core/ids.ts. Blanks, fractional floats and floats above",
    '    2**53 become <NA>: a float that large has already been rounded to a different id.',
    '    """',
    '    column = pd.Series(values)',
    '    codes, uniques = pd.factorize(column.array)',
    '    if len(uniques) * 2 < len(column):',
    '        # Cast each distinct value once; an edge list repeats a neuron once per partner.',
    '        text = coda_id_column(pd.Series(uniques)).array',
    '        return pd.Series(pd.api.extensions.take(text, codes, allow_fill=True), index=column.index)',
    '    if pd.api.types.is_float_dtype(column):',
    '        column = column.mask((column % 1 != 0) | (column.abs() > 2**53))',
    "    elif pd.api.types.infer_dtype(column, skipna=True) in ('floating', 'mixed-integer-float', 'mixed'):",
    '        # Same rule for floats mixed with other values (e.g. 10003.0 in a CSV column with',
    '        # blanks), without turning 18-digit integers into floats.',
    '        column = column.map(lambda v: v if not isinstance(v, float) else',
    '                            int(v) if v.is_integer() and abs(v) <= 2**53 else None)',
    "    text = coda_ids(pd.DataFrame({'id': column}), 'id')['id']",
    '    if pd.api.types.is_numeric_dtype(column):',
    '        return text',
    '    text = text.str.strip()',
    "    return text.mask(text == '')",
  ],
})

/**
 * Ids to compare against a column, as text or — where the column is an integer one — as the
 * integers that match it. Shared by both reading surfaces, so a file and a frame agree about which
 * ids a lookup names.
 */
registerHelper({
  name: 'coda_typed_ids',
  needs: ['coda_id_column'],
  requires: [['pandas']],
  source: [
    'def coda_typed_ids(ids, integer):',
    '    """Return ids for matching against a column: as text, or as integers for an integer column."""',
    '    text = coda_id_column(pd.Series(list(ids), dtype=object)).dropna()',
    '    if integer:',
    "        return [int(i) for i in text[text.str.fullmatch(r'-?\\d+')]]",
    '    return list(text)',
  ],
})

/**
 * Whether a column's name says it holds ids — `isIdentifierColumn` in `core/ids.ts`, ported: its
 * last word, camelCase or snake_case, is `id` or `ids`. What `CodaTableFile` casts to text when an
 * export was taken before the canvas had read the file's footer, where no list of text columns
 * could be written into the cell.
 */
registerHelper({
  name: 'coda_is_id_name',
  requires: [['re']],
  source: [
    'def coda_is_id_name(name):',
    '    """Check whether a column name marks an id column, i.e. its last word is `id` or `ids`."""',
    "    spaced = re.sub(r'([a-z0-9])([A-Z])', r'\\1 \\2', name)",
    "    words = [w for w in re.split(r'[^A-Za-z0-9]+', spaced) if w]",
    "    return bool(words) and words[-1].lower() in ('id', 'ids')",
  ],
})

/**
 * A Link Table's file or Delta table: a reference, read the way Coda reads it.
 *
 * `read(columns, where, limit, any_of)` takes only the columns asked for and, with `where`
 * ({column: ids}, ANDed — or, with `any_of`, either), only the rows holding one of the ids:
 *
 *  - **Parquet** by its row-group statistics through `pq.read_table(..., filters=)`, which is the
 *    notebook's half of Coda's block skipping;
 *  - **Feather** by a filter over a memory-mapped read, Feather keeping no statistics;
 *  - **Delta** as SQL through delta-rs' `QueryBuilder`, pinned to the `version` the canvas read.
 *    Not `to_pyarrow_dataset`, which refuses a table with deletion vectors and reads a
 *    column-mapped one as nulls.
 *
 * A lookup naming no ids answers an empty frame, the canvas' rule that an unconfigured lookup
 * reads nothing; a cap with no lookup reads only the first blocks. The schema is the footer's — a
 * Delta table's its log's — read once. Text columns are cast by Arrow before pandas sees them,
 * digit for digit (invariant 8). Checked by `scripts/probe-py-helpers.py` against the fixtures
 * `data/files` tests with, the Delta tables among them.
 */
registerHelper({
  name: 'CodaTableFile',
  needs: ['coda_typed_ids', 'coda_is_id_name'],
  requires: [
    ['copy'],
    ['pandas'],
    ['pyarrow'],
    ['pyarrowParquet'],
    ['pyarrowFeather'],
    ['pyarrowCompute'],
    ['fsspec'],
  ],
  source: [
    'class CodaTableFile:',
    '    """Read a Parquet or Feather file, or a Delta table, the way Coda\'s Link Table does.',
    '',
    '    `read` fetches only the requested columns and, given `where` ({column: ids}), only the',
    '    rows matching those ids in all columns (or in any, with any_of=True). Parquet and Delta',
    '    files are skipped using their statistics, so a lookup in a sorted synapse table reads',
    '    only a fraction of it. A Delta table is read at `version`.',
    '',
    '    A lookup with an empty id list returns an empty frame. Id columns come back as exact',
    '    text so that 18-digit ids survive; pass text=False to keep them as stored.',
    '    """',
    '',
    "    def __init__(self, location, format='parquet', text_columns=None, version=None):",
    '        self.location = location',
    '        self.format = format',
    '        # The Delta table version the canvas read, so later commits do not change the result.',
    '        self.version = version',
    '        self.text_columns = None if text_columns is None else set(text_columns)',
    '        self._schema = None',
    '        self._remote = None',
    '        self._table = None',
    '        # Filter Table conditions as (columns, keep), where keep maps a frame to a row mask.',
    '        self.conditions = []',
    '',
    '    def where(self, columns, keep):',
    '        """Return a copy with a row condition added, as a Filter Table after a Link Table.',
    '',
    '        Nothing is read here; later reads drop the rows that fail the condition.',
    '        """',
    '        other = copy.copy(self)',
    '        other.conditions = self.conditions + [(list(columns), keep)]',
    '        return other',
    '',
    '    def _open(self):',
    '        # pyarrow reads gs:// and s3:// itself; https:// goes through fsspec, which serves',
    '        # byte ranges. The handle is reused so the footer is fetched only once.',
    "        if self.location.startswith(('http://', 'https://')):",
    '            if self._remote is None:',
    "                self._remote = fsspec.open(self.location, 'rb').open()",
    '            return self._remote',
    '        return self.location',
    '',
    '    def schema(self):',
    "        # Read once, without reading rows: from a Delta table's log or a file's footer",
    "        # (Feather is Arrow's IPC file format).",
    '        if self._schema is None:',
    "            if self.format == 'delta':",
    '                self._schema = pa.schema(self._delta().schema().to_arrow())',
    "            elif self.format == 'parquet':",
    '                self._schema = pq.read_schema(self._open())',
    '            else:',
    '                self._schema = pa.ipc.open_file(self._open()).schema',
    '        return self._schema',
    '',
    '    def _delta(self):',
    '        # Public buckets are read anonymously, as on the canvas; delta-rs expects gs:// for GCS.',
    '        if self._table is None:',
    "            uri = self.location.replace('https://storage.googleapis.com/', 'gs://', 1)",
    "            public = uri.startswith(('gs://', 's3://'))",
    '            self._table = DeltaTable(uri, version=self.version,',
    "                                     storage_options={'skip_signature': 'true'} if public else None)",
    '        return self._table',
    '',
    '    def _delta_batches(self, columns, clauses, any_of, limit=None):',
    '        # Query with SQL; id lookups become IN clauses so delta-rs can skip files by their stats.',
    "        quote = lambda name: '\"' + name.replace('\"', '\"\"') + '\"'",
    '        literal = lambda v: str(v) if isinstance(v, int) else "\'" + str(v).replace("\'", "\'\'") + "\'"',
    "        sql = 'SELECT ' + (', '.join(map(quote, columns)) if columns else '*') + ' FROM t'",
    '        tests = [f\'{quote(name)} IN ({", ".join(map(literal, values))})\' for name, _, values in clauses if values]',
    '        if tests:',
    "            sql += ' WHERE ' + (' OR ' if any_of else ' AND ').join(tests)",
    '        if limit:',
    "            sql += f' LIMIT {int(limit)}'",
    "        return pa.RecordBatchReader.from_stream(QueryBuilder().register('t', self._delta()).execute(sql))",
    '',
    '    def names(self):',
    '        return self.schema().names',
    '',
    '    def read(self, columns=None, where=None, limit=None, text=True, any_of=False):',
    '        # text=False keeps id columns as stored (grouping int64 is much faster than strings).',
    '        # any_of=True matches rows with an id in any of the where columns instead of all.',
    '        schema = self.schema()',
    '        wanted = None if columns is None else list(dict.fromkeys(columns))',
    '        tested = [c for cols, _ in self.conditions for c in cols]',
    '        needed = None if wanted is None else list(dict.fromkeys(wanted + tested))',
    "        clauses = [(name, 'in', coda_typed_ids(ids, pa.types.is_integer(schema.field(name).type)))",
    '                   for name, ids in (where or {}).items()]',
    '        if clauses and (all if any_of else any)(not values for _, _, values in clauses):',
    '            table = schema.empty_table()',
    '        elif not clauses and limit:',
    '            # A limit without a lookup reads only the first blocks, as the canvas does.',
    '            table = self._head(needed, limit)',
    "        elif self.format == 'delta':",
    '            table = self._kept(self._delta_batches(needed, clauses, any_of).read_all())',
    "        elif self.format == 'parquet':",
    '            filters = [[c] for c in clauses if c[2]] if any_of else clauses',
    '            table = self._kept(pq.read_table(self._open(), columns=needed, filters=filters or None))',
    '        else:',
    '            names = None if needed is None else list(dict.fromkeys(needed + [c for c, _, _ in clauses]))',
    '            table = feather.read_table(self._open(), columns=names, memory_map=True)',
    '            masks = []',
    '            for name, _, values in clauses:',
    '                column = table[name]',
    '                if pa.types.is_dictionary(column.type):',
    '                    column = column.cast(column.type.value_type)',
    '                # Cast (rather than construct) so text ids can match a float column.',
    '                masks.append(pc.is_in(column, value_set=pa.array(values).cast(column.type)))',
    '            if masks:',
    '                mask = masks[0]',
    '                for more in masks[1:]:',
    '                    mask = (pc.or_ if any_of else pc.and_)(mask, more)',
    '                table = table.filter(mask)',
    '            table = self._kept(table)',
    '        if wanted is not None:',
    '            table = table.select(wanted)',
    '        if limit:',
    '            table = table.slice(0, limit)',
    '        return (self._as_text(table) if text else table).to_pandas()',
    '',
    '    def _as_text(self, table):',
    '        # Cast with Arrow before pandas sees the column, so int64 ids convert exactly.',
    '        for name in self._text_columns() & set(table.column_names):',
    '            at = table.column_names.index(name)',
    '            table = table.set_column(at, name, table[name].cast(pa.string()))',
    '        return table',
    '',
    '    def _head(self, columns, limit):',
    '        batches, held = [], 0',
    "        if self.format == 'delta':",
    '            # Without conditions the limit goes into the query, so the scan stops early.',
    '            source = self._delta_batches(columns, [], False, None if self.conditions else limit)',
    "        elif self.format == 'parquet':",
    '            source = pq.ParquetFile(self._open()).iter_batches(columns=columns)',
    '        else:',
    '            # Decode (and, over a URL, fetch) only the requested columns.',
    '            names = self.schema().names',
    '            fields = None if columns is None else [names.index(c) for c in columns]',
    '            reader = pa.ipc.open_file(',
    '                self._open(), options=pa.ipc.IpcReadOptions(included_fields=fields))',
    '            source = (reader.get_batch(i) for i in range(reader.num_record_batches))',
    '        for batch in source:',
    '            # Count rows after applying conditions, as the canvas does.',
    '            kept = self._kept(pa.Table.from_batches([batch]))',
    '            batches.append(kept)',
    '            held += kept.num_rows',
    '            if held >= limit:',
    '                break',
    '        return pa.concat_tables(batches) if batches else self.schema().empty_table()',
    '',
    '    def _kept(self, table):',
    '        # Apply the conditions to ids as text (as the canvas does, regardless of `text`)',
    '        # and drop the rows that fail any of them.',
    '        if not self.conditions:',
    '            return table',
    '        names = list(dict.fromkeys(c for cols, _ in self.conditions for c in cols))',
    '        frame = self._as_text(table.select(names)).to_pandas()',
    '        mask = pd.Series(True, index=frame.index)',
    '        for _, keep in self.conditions:',
    '            mask &= keep(frame).fillna(False).astype(bool)',
    '        return table.filter(pa.array(mask.to_numpy()))',
    '',
    '    def _text_columns(self):',
    '        # Use the columns the canvas listed; otherwise every integer column whose name marks',
    "        # it as an id (Coda's own rule), so ids never arrive as int64.",
    '        if self.text_columns is None:',
    '            self.text_columns = {',
    '                field.name for field in self.schema()',
    '                if pa.types.is_integer(field.type) and coda_is_id_name(field.name)',
    '            }',
    '        return self.text_columns',
  ],
})

/**
 * A pandas frame with `CodaTableFile`'s reading surface, so a Custom Dataset reads a part one way
 * whether it was wired as a table or as a file — the `TableValue`/`TableFileValue` pair the canvas'
 * lookups already treat alike.
 */
registerHelper({
  name: 'CodaFrameTable',
  needs: ['coda_id_column', 'coda_typed_ids'],
  requires: [['pandas']],
  source: [
    'class CodaFrameTable:',
    '    """Wrap a pandas frame so it can be read like a `CodaTableFile`."""',
    '',
    '    def __init__(self, frame):',
    '        self.frame = frame',
    '        self._keys = {}',
    '',
    '    def names(self):',
    '        return list(self.frame.columns)',
    '',
    '    def _key(self, name):',
    '        # Convert each key column to text once and cache it.',
    '        if name not in self._keys:',
    '            self._keys[name] = coda_id_column(self.frame[name])',
    '        return self._keys[name]',
    '',
    '    def read(self, columns=None, where=None, limit=None, text=True, any_of=False):',
    '        # Select by position, not label: a frame may have repeated index labels.',
    '        keep = None',
    '        for name, ids in (where or {}).items():',
    '            integer = pd.api.types.is_integer_dtype(self.frame[name])',
    '            key = self.frame[name] if integer else self._key(name)',
    '            hits = key.isin(coda_typed_ids(ids, integer)).to_numpy()',
    '            keep = hits if keep is None else (keep | hits if any_of else keep & hits)',
    '        frame = self.frame if keep is None else self.frame[keep]',
    '        if columns is not None:',
    '            frame = frame[list(dict.fromkeys(columns))]',
    '        return frame.head(limit) if limit else frame',
  ],
})

/**
 * navis 2's mesh class where it has one, `MeshNeuron` where it does not.
 *
 * `navis.Mesh` is navis 2's name, with `MeshNeuron` kept as a warning alias; PyPI's newest release
 * is still 1.12, which has only `MeshNeuron`. So a cell written against either name fails for half
 * its readers — `AttributeError` on a plain `pip install navis`, a deprecation warning on the git
 * build `export-requirements.txt` pins. Found by an audit: `check-export.py` resolved the name
 * against the git build and passed.
 */
registerHelper({
  name: 'coda_mesh',
  requires: [['navis']],
  source: [
    'def coda_mesh(*args, **kwargs):',
    '    """Make a navis mesh neuron (`navis.Mesh` in navis 2, `navis.MeshNeuron` before)."""',
    "    return (getattr(navis, 'Mesh', None) or navis.MeshNeuron)(*args, **kwargs)",
  ],
})

/**
 * A Neuroglancer precomputed bucket's geometry, through cloudvolume.
 *
 * cloudvolume rather than `navis.read_precomputed`: the latter reads a local directory, and a
 * bucket is a URL. Meshes are `coda_mesh` (`navis.Mesh`, or `MeshNeuron` before navis 2) at full
 * resolution, the canvas' default; a skeleton is built by `navis.edges2neuron`,
 * since navis will not take cloudvolume's `Skeleton` object itself. Both in nanometres, read off
 * the bucket's `info`. A batch that fails is **halved** until the segments with nothing are found,
 * so one missing segment costs a few requests rather than one per id; those are left out and
 * counted, as the canvas warns. Checked live against `gs://flywire_v141_m783`.
 */
registerHelper({
  name: 'CodaPrecomputed',
  needs: ['coda_mesh'],
  requires: [['cloudvolume', 'CloudVolume'], ['navis']],
  source: [
    'class CodaPrecomputed:',
    '    """Fetch meshes and skeletons from a Neuroglancer precomputed bucket via cloudvolume.',
    '',
    '    Returns navis neurons in nanometres. Segments missing from the bucket are skipped and',
    '    counted, as on the canvas.',
    '    """',
    '',
    '    def __init__(self, url):',
    '        self.url = url',
    '        self._cv = None',
    '',
    '    @property',
    '    def cv(self):',
    '        if self._cv is None:',
    '            self._cv = CloudVolume(self.url, use_https=True, progress=False)',
    '        return self._cv',
    '',
    '    def _each(self, ids, fetch, what):',
    '        # Fetch the whole batch at once; if it fails, split it in half and retry, so a few',
    '        # missing segments cost a few extra requests, not one request per id.',
    '        def attempt(batch):',
    '            try:',
    '                return fetch(batch), []',
    '            except Exception as error:',
    '                if len(batch) == 1:',
    '                    errors.append(error)',
    '                    return {}, batch',
    '                half = len(batch) // 2',
    '                (a, lost_a), (b, lost_b) = attempt(batch[:half]), attempt(batch[half:])',
    '                return {**a, **b}, lost_a + lost_b',
    '',
    '        errors = []',
    '        ids = [int(i) for i in ids]',
    '        found, missing = attempt(ids) if ids else ({}, [])',
    '        if missing:',
    '            # Usually segments absent from the bucket; the last error shows if not.',
    "            print(f'{len(missing)} of {len(ids)} segments could not be read as {what} from '",
    "                  f'{self.url} (last error: {errors[-1]!r})')",
    '        return found',
    '',
    '    def meshes(self, ids):',
    "        found = self._each(ids, lambda batch: dict(self.cv.mesh.get(batch)), 'mesh')",
    '        return navis.NeuronList(',
    '            [coda_mesh(mesh, id=i, units="nm") for i, mesh in found.items()]',
    '        )',
    '',
    '    def skeletons(self, ids):',
    '        def fetch(batch):',
    '            return {int(s.id): s for s in self.cv.skeleton.get(batch)}',
    '',
    '        neurons = []',
    "        for i, sk in self._each(ids, fetch, 'skeleton').items():",
    '            tree = navis.edges2neuron(sk.edges, vertices=sk.vertices, validate=True)',
    '            tree.id = i',
    "            tree.units = 'nm'",
    '            neurons.append(tree)',
    '        return navis.NeuronList(neurons)',
  ],
})

/**
 * Coda's Custom Dataset: the parts, and the questions each answers — `CompositeSource` and the
 * wired edge set, ported.
 *
 * `labels` is the neuron table — `neuron_table` is `neuronTable` in `data/custom/neurons.ts` — or,
 * with none, the edge list's ids (`edgeListNeurons`). `connectivity` is `coda_walk` with a filter of
 * the edge list as its hop, and the canvas' `Include fragments`. `synapses` and `synapses_between`
 * are the lookups of `data/custom/synapses.ts`, positions scaled by the voxel size, `polarity` and
 * `confidence` left empty on the second for that module's reasons, and both ends pushed into one
 * read where both are bound. Geometry is a function of the ids per socket, which the emitter builds
 * at export from `geometryCall` — so a lender with no route is a note there, never a run-time error.
 */
registerHelper({
  name: 'CodaCustomDataset',
  needs: ['coda_id_column', 'coda_typed_ids', 'CodaTableFile', 'CodaFrameTable', 'coda_walk'],
  requires: [['pandas']],
  source: [
    'class CodaCustomDataset:',
    '    """Coda\'s Custom Dataset: a dataset assembled from your own tables and files.',
    '',
    '    `labels` is the neuron table (one row per neuron, keyed by text `neuronId`) or, if none',
    '    was wired, every id in the edge list. `edges` and `synapses` each name a frame or a',
    '    `CodaTableFile` plus the columns to read. Without an edge list, connectivity counts the',
    "    synapse table's rows per pair. `meshes` and `skeletons` are functions of the ids.",
    '    """',
    '',
    "    def __init__(self, neurons=None, id_column='neuronId', edges=None, synapses=None,",
    '                 meshes=None, skeletons=None):',
    '        self._labels = None if neurons is None else self.neuron_table(neurons, id_column)',
    '        self._labels_derived = neurons is None',
    '        self.edges = self._part(edges)',
    '        self.synapses_spec = self._part(synapses)',
    '        self.mesh_source = meshes',
    '        self.skeleton_source = skeletons',
    '        self._edge_list = None',
    '        self._type_map = None',
    '',
    '    @staticmethod',
    '    def _part(spec):',
    "        if spec is None or isinstance(spec['source'], CodaTableFile):",
    '            return spec',
    "        return {**spec, 'source': CodaFrameTable(spec['source'])}",
    '',
    '    @staticmethod',
    '    def neuron_table(frame, id_column):',
    '        """Turn a table into the neuron table, keyed by `id_column`.',
    '',
    '        The id column becomes the first column, `neuronId`, as text. Rows without a valid id',
    '        are dropped; for repeated ids the first row is kept.',
    '        """',
    '        ids = coda_id_column(frame[id_column]).values',
    "        rest = [c for c in frame.columns if c not in (id_column, 'neuronId')]",
    '        table = frame[rest].copy()',
    "        table.insert(0, 'neuronId', ids)",
    "        return table[table['neuronId'].notna()].drop_duplicates(subset='neuronId').reset_index(drop=True)",
    '',
    '    # ---- neurons ---------------------------------------------------------------------------',
    '',
    '    @property',
    '    def labels(self):',
    '        if self._labels is None:',
    '            if self.edges is None and self.synapses_spec is None:',
    '                raise ValueError(',
    "                    'This Custom Dataset has no neuron table, so it cannot say which neurons it '",
    "                    'has. Wire a table into Neurons, or an edge list into Edges.'",
    '                )',
    '            edges = self.edge_list()',
    "            ids = pd.unique(pd.concat([edges['preId'], edges['postId']], ignore_index=True))",
    "            self._labels = pd.DataFrame({'neuronId': ids})",
    '        return self._labels',
    '',
    '    def lookup(self, ids):',
    '        """Return the neuron table rows for these ids.',
    '',
    '        Without a neuron table, the ids are returned as given.',
    '        """',
    '        wanted = coda_typed_ids(ids, False)',
    '        if self._labels_derived:',
    "            return pd.DataFrame({'neuronId': list(dict.fromkeys(wanted))})",
    "        return self.labels[self.labels['neuronId'].isin(wanted)].reset_index(drop=True)",
    '',
    '    def _types(self):',
    '        if self._type_map is None:',
    '            # Without a neuron table there are no types (and none are looked up).',
    "            typed = not self._labels_derived and 'type' in self.labels.columns",
    "            self._type_map = (dict(zip(self.labels['neuronId'], self.labels['type']))",
    '                              if typed else {})',
    '        return self._type_map',
    '',
    '    # ---- connectivity ----------------------------------------------------------------------',
    '',
    '    def edge_list(self):',
    '        """Return every connection as preId, postId, weight, with ids as text.',
    '',
    '        Repeated pairs are summed. Without a weight column (a synapse table, or an edge list',
    '        that has no such column) each row counts as one.',
    '        """',
    '        if self._edge_list is None:',
    '            spec = self.edges or self.synapses_spec',
    '            if spec is None:',
    "                raise ValueError('This Custom Dataset has no connectivity. Wire an edge list '",
    "                                 'into its Edges socket, or a synapse table into Synapses.')",
    "            source = spec['source']",
    "            weight = self.edges.get('weight') if self.edges else None",
    '            if weight is not None and weight not in source.names():',
    "                print(f'The edge list has no column {weight!r}, so each row counts as one.')",
    '                weight = None',
    "            keys = [spec['pre'], spec['post']]",
    '            frame = source.read(columns=keys + ([weight] if weight else []), text=False)',
    '            # Aggregate raw pairs first so ids are converted once per edge, not once per row.',
    '            if weight:',
    "                frame = frame.assign(**{weight: pd.to_numeric(frame[weight], errors='coerce')})",
    '                pairs = frame.groupby(keys, sort=False)[weight].sum(min_count=1)',
    '            else:',
    '                pairs = frame.groupby(keys, sort=False).size()',
    "            pairs = pairs.reset_index(name='weight')",
    '            edges = pd.DataFrame({',
    "                'preId': coda_id_column(pairs[keys[0]]),",
    "                'postId': coda_id_column(pairs[keys[1]]),",
    "                'weight': pairs['weight'],",
    '            }).dropna()',
    '            if all(pd.api.types.is_integer_dtype(pairs[k]) for k in keys):',
    '                self._edge_list = edges.reset_index(drop=True)',
    '            else:',
    "                # Merge pairs whose ids differed only in spelling (e.g. 1 and ' 1').",
    "                self._edge_list = edges.groupby(['preId', 'postId'], as_index=False, sort=False)['weight'].sum()",
    '        return self._edge_list',
    '',
    '    def connectivity(self, seed_ids, direction, hops=1, min_weight=1, include_fragments=False):',
    '        """Find partners over the edge list, as Coda\'s Connectivity node does.',
    '',
    '        Without include_fragments, partners must be in the neuron table (seeds are exempt).',
    '        Without a neuron table, every partner is kept.',
    '        """',
    '        edges = self.edge_list()',
    "        edges = edges[edges['weight'] >= min_weight]",
    '        seeds = set(coda_typed_ids(seed_ids, False))',
    '        keep = (None if include_fragments or self._labels_derived',
    "                else set(self.labels['neuronId']) | seeds)",
    '        types = self._types()',
    '',
    '        def one_hop(ids, way):',
    "            near, far = ('preId', 'postId') if way == 'downstream' else ('postId', 'preId')",
    '            step = edges[edges[near].isin(ids)]',
    '            if keep is not None:',
    '                step = step[step[far].isin(keep)]',
    "            return step.assign(preType=step['preId'].map(types), postType=step['postId'].map(types))",
    '',
    '        return coda_walk(seeds, direction, hops, one_hop)',
    '',
    '    # ---- synapses --------------------------------------------------------------------------',
    '',
    '    def _synapse_rows(self, where, carry=True, any_of=False):',
    "        \"\"\"Return synapse rows matching {'pre': ids, 'post': ids}: both ends, or either",
    '        with any_of=True."""',
    '        spec = self.synapses_spec',
    '        if spec is None:',
    "            raise ValueError('This Custom Dataset has no synapses: wire a synapse table into its '",
    "                             'Synapses socket.')",
    "        carried = list(spec['carry']) if carry else []",
    '        # Skip carried columns whose names clash with the ones written here (e.g. a raw',
    '        # voxel `z` would overwrite the one in nanometres).',
    "        clashing = [c for c in carried if c in ('pre', 'post', 'x', 'y', 'z')]",
    '        if clashing:',
    "            print(f'Not carried, their names being taken by the position and ends: {clashing}')",
    '            carried = [c for c in carried if c not in clashing]',
    "        frame = spec['source'].read(",
    "            columns=[spec['pre'], spec['post'], *spec['position'], *carried],",
    '            where={spec[side]: ids for side, ids in where.items()},',
    '            any_of=any_of,',
    '        )',
    "        (vx, vy, vz), (x, y, z) = spec['voxel'], spec['position']",
    '        return pd.DataFrame({',
    "            'pre': coda_id_column(frame[spec['pre']]).values,",
    "            'post': coda_id_column(frame[spec['post']]).values,",
    "            'x': frame[x].astype(float).values * vx,",
    "            'y': frame[y].astype(float).values * vy,",
    "            'z': frame[z].astype(float).values * vz,",
    '            **{c: frame[c].values for c in carried},',
    '        })',
    '',
    '    def synapses(self, ids, polarity=None):',
    '        """Fetch the synapses of a set of neurons.',
    '',
    '        neuronId is the queried neuron, partnerId the other end, x/y/z are in nm, followed by',
    '        any carried columns. Both polarities are returned unless `polarity` is given.',
    '        """',
    "        sides = [polarity] if polarity else ['pre', 'post']",
    '        # Read both ends at once, then split by end. Ids are matched as text and as numbers,',
    '        # since an integer column was matched numerically.',
    '        rows = self._synapse_rows({side: ids for side in sides}, any_of=True)',
    '        wanted = set(coda_typed_ids(ids, False)) | {str(i) for i in coda_typed_ids(ids, True)}',
    '        frames = []',
    '        for side in sides:',
    "            other = 'post' if side == 'pre' else 'pre'",
    '            frames.append(rows[rows[side].isin(wanted)]',
    "                          .rename(columns={side: 'neuronId', other: 'partnerId'})",
    '                          .assign(polarity=side))',
    '        out = pd.concat(frames, ignore_index=True)',
    "        first = ['neuronId', 'partnerId', 'polarity', 'x', 'y', 'z']",
    '        return out[first + [c for c in out.columns if c not in first]]',
    '',
    '    def synapses_between(self, sources=None, targets=None, include_fragments=True):',
    '        """Fetch the synapses from sources onto targets; neuronId is the presynaptic end.',
    '',
    '        polarity and confidence are left empty: the table does not say which end a position',
    '        belongs to, and has no confidence scale. If only one side is given and',
    '        include_fragments is off, the other end must be in the neuron table (if there is one).',
    '        """',
    "        where = {side: ids for side, ids in (('pre', sources), ('post', targets)) if ids is not None}",
    '        if not where:',
    "            raise ValueError('Synapses between two sets needs sources, targets or both.')",
    '        rows = self._synapse_rows(where, carry=False)',
    '        if not include_fragments and len(where) == 1 and not self._labels_derived:',
    "            open_end = 'post' if 'pre' in where else 'pre'",
    "            rows = rows[rows[open_end].isin(self.labels['neuronId'])].reset_index(drop=True)",
    '        types = self._types()',
    '        return pd.DataFrame({',
    "            'neuronId': rows['pre'].values,",
    "            'type': rows['pre'].map(types).values,",
    "            'partnerId': rows['post'].values,",
    "            'partnerType': rows['post'].map(types).values,",
    "            'polarity': None,",
    "            'confidence': None,",
    "            'x': rows['x'].values,",
    "            'y': rows['y'].values,",
    "            'z': rows['z'].values,",
    '        })',
    '',
    '    # ---- geometry --------------------------------------------------------------------------',
    '',
    '    def _geometry(self, source, what, ids):',
    '        if source is None:',
    "            raise ValueError(f'This Custom Dataset has no {what} in this notebook: nothing is '",
    "                             f'wired into its {what.capitalize()} socket, or what is wired there '",
    "                             f'has no notebook form (the Custom Dataset cell says so).')",
    '        return source(ids)',
    '',
    '    def meshes(self, ids):',
    "        return self._geometry(self.mesh_source, 'meshes', ids)",
    '',
    '    def skeletons(self, ids):',
    "        return self._geometry(self.skeleton_source, 'skeletons', ids)",
  ],
})
