/**
 * Generated Python helpers for the Custom Dataset and the table files it reads.
 *
 * The counterpart of `caveHelpers.ts` for the parts a Custom Dataset is assembled from: a table
 * file read by columns and ids, a precomputed bucket's geometry, and the class standing in for
 * `CompositeSource` so a downstream cell has one object to ask. Each mirrors a piece of
 * `src/data/files`, `src/data/edges` or `src/data/custom`, and that pairing is the thing to keep
 * true. `pnpm probe:helpers` runs the Custom Dataset golden whole against files it writes.
 */

import { registerHelper } from './registry'

/**
 * An id column as exact text, or `<NA>` where a value is no id — `idText` in `core/ids.ts`, over a
 * column at once.
 *
 * Built on `coda_ids` rather than beside it, so the notebook has one cast: this adds only `idText`'s
 * refusals — a blank, a fractional float, and a float past 2^53, which is already a different
 * neuron and would be hidden by turning it into text. Vectorised because it meets whole tables,
 * and cast once per distinct value where they repeat — an edge list's ends, a synapse table's.
 */
registerHelper({
  name: 'coda_id_column',
  needs: ['coda_ids'],
  requires: [['pandas']],
  source: [
    'def coda_id_column(values):',
    '    """An id column as exact text, or <NA> where a value is no id: `idText` in Coda\'s',
    '    core/ids.ts, over a whole column at once.',
    '',
    "    `coda_ids`' cast, then a blank is no id, and neither is a fractional float or one past",
    '    2**53 — already a different neuron, which turning it into text would hide.',
    '    """',
    '    column = pd.Series(values)',
    '    codes, uniques = pd.factorize(column.array)',
    '    if len(uniques) * 2 < len(column):',
    '        # Each distinct value cast once: an edge list names a neuron once per partner.',
    '        text = coda_id_column(pd.Series(uniques)).array',
    '        return pd.Series(pd.api.extensions.take(text, codes, allow_fill=True), index=column.index)',
    '    if pd.api.types.is_float_dtype(column):',
    '        column = column.mask((column % 1 != 0) | (column.abs() > 2**53))',
    "    elif pd.api.types.infer_dtype(column, skipna=True) in ('floating', 'mixed-integer-float', 'mixed'):",
    '        # The same rule for a float among other values — a list of ids, a CSV column with a',
    '        # blank arriving as 10003.0 — without widening an eighteen-digit integer to a float.',
    '        column = column.map(lambda v: v if not isinstance(v, float) else',
    '                            int(v) if v.is_integer() and abs(v) <= 2**53 else None)',
    "    text = coda_ids(pd.DataFrame({'id': column}), 'id')['id']",
    '    if pd.api.types.is_numeric_dtype(column):',
    '        return text',
    '    text = text.str.strip()',
    "    return text.mask(text == '')",
  ],
})

/**
 * Ids to compare against a column, as text or — where the column is an integer one — as the
 * integers that match it. Shared by both reading surfaces, so a file and a frame agree about which
 * ids a lookup names.
 */
registerHelper({
  name: 'coda_typed_ids',
  needs: ['coda_id_column'],
  requires: [['pandas']],
  source: [
    'def coda_typed_ids(ids, integer):',
    '    """Ids to compare against a column: exact text, or integers where the column is one."""',
    '    text = coda_id_column(pd.Series(list(ids), dtype=object)).dropna()',
    '    if integer:',
    "        return [int(i) for i in text[text.str.fullmatch(r'-?\\d+')]]",
    '    return list(text)',
  ],
})

/**
 * Whether a column's name says it holds ids — `isIdentifierColumn` in `core/ids.ts`, ported: its
 * last word, camelCase or snake_case, is `id` or `ids`. What `CodaTableFile` casts to text when an
 * export was taken before the canvas had read the file's footer, where no list of text columns
 * could be written into the cell.
 */
registerHelper({
  name: 'coda_is_id_name',
  requires: [['re']],
  source: [
    'def coda_is_id_name(name):',
    '    """Whether a column name reads as ids: its last word is `id` or `ids`."""',
    "    spaced = re.sub(r'([a-z0-9])([A-Z])', r'\\1 \\2', name)",
    "    words = [w for w in re.split(r'[^A-Za-z0-9]+', spaced) if w]",
    "    return bool(words) and words[-1].lower() in ('id', 'ids')",
  ],
})

/**
 * A Link Table's file or Delta table: a reference, read the way Coda reads it.
 *
 * `read(columns, where, limit, any_of)` takes only the columns asked for and, with `where`
 * ({column: ids}, ANDed — or, with `any_of`, either), only the rows holding one of the ids:
 *
 *  - **Parquet** by its row-group statistics through `pq.read_table(..., filters=)`, which is the
 *    notebook's half of Coda's block skipping;
 *  - **Feather** by a filter over a memory-mapped read, Feather keeping no statistics;
 *  - **Delta** as SQL through delta-rs' `QueryBuilder`, pinned to the `version` the canvas read.
 *    Not `to_pyarrow_dataset`, which refuses a table with deletion vectors and reads a
 *    column-mapped one as nulls.
 *
 * A lookup naming no ids answers an empty frame, the canvas' rule that an unconfigured lookup
 * reads nothing; a cap with no lookup reads only the first blocks. The schema is the footer's — a
 * Delta table's its log's — read once. Text columns are cast by Arrow before pandas sees them,
 * digit for digit (invariant 8). Checked by `scripts/probe-py-helpers.py` against the fixtures
 * `data/files` tests with, the Delta tables among them.
 */
registerHelper({
  name: 'CodaTableFile',
  needs: ['coda_typed_ids', 'coda_is_id_name'],
  requires: [
    ['copy'],
    ['pandas'],
    ['pyarrow'],
    ['pyarrowParquet'],
    ['pyarrowFeather'],
    ['pyarrowCompute'],
    ['fsspec'],
  ],
  source: [
    'class CodaTableFile:',
    '    """A Parquet or Feather file, or a Delta table, read the way Coda\'s Link Table reads it.',
    '',
    '    `read` fetches only the columns asked for and, given `where` ({column: ids}, ANDed, or',
    '    with any_of=True either), only the rows holding one of the ids — from Parquet by its',
    '    row-group statistics and from a Delta table by the statistics in its log, so a lookup in',
    '    a sorted synapse table reads a fraction of it. A Delta table is read at `version`.',
    '    A lookup naming no ids gets an empty frame, never the whole file; text=False leaves id',
    '    columns as stored. Columns Coda reads as text come back as exact',
    '    decimal text: an eighteen-digit id through a float is a different neuron.',
    '    """',
    '',
    "    def __init__(self, location, format='parquet', text_columns=None, version=None):",
    '        self.location = location',
    '        self.format = format',
    "        # A Delta table's version, the one the canvas read — so a commit since changes nothing.",
    '        self.version = version',
    '        self.text_columns = None if text_columns is None else set(text_columns)',
    '        self._schema = None',
    '        self._remote = None',
    '        self._table = None',
    "        # A Filter Table's conditions: (columns, keep), keep a function from a frame to a mask.",
    '        self.conditions = []',
    '',
    '    def where(self, columns, keep):',
    '        """This file with a row condition added, read nowhere: every read below keeps only the',
    '        rows passing it, out of the rows it fetched — as a Filter Table below a Link Table does."""',
    '        other = copy.copy(self)',
    '        other.conditions = self.conditions + [(list(columns), keep)]',
    '        return other',
    '',
    '    def _open(self):',
    '        # pyarrow reads gs:// and s3:// itself; a plain https:// file goes through fsspec,',
    '        # which serves pyarrow the byte ranges it asks for — one handle, reused, so a read does',
    '        # not fetch the footer again.',
    "        if self.location.startswith(('http://', 'https://')):",
    '            if self._remote is None:',
    "                self._remote = fsspec.open(self.location, 'rb').open()",
    '            return self._remote',
    '        return self.location',
    '',
    '    def schema(self):',
    "        # Once, and without a row read: a Delta table's is in its log, a file's in its footer —",
    "        # Feather being Arrow's IPC file format.",
    '        if self._schema is None:',
    "            if self.format == 'delta':",
    '                self._schema = pa.schema(self._delta().schema().to_arrow())',
    "            elif self.format == 'parquet':",
    '                self._schema = pq.read_schema(self._open())',
    '            else:',
    '                self._schema = pa.ipc.open_file(self._open()).schema',
    '        return self._schema',
    '',
    '    def _delta(self):',
    '        # A public bucket read anonymously, as the canvas reads it; delta-rs names GCS gs://.',
    '        if self._table is None:',
    "            uri = self.location.replace('https://storage.googleapis.com/', 'gs://', 1)",
    "            public = uri.startswith(('gs://', 's3://'))",
    '            self._table = DeltaTable(uri, version=self.version,',
    "                                     storage_options={'skip_signature': 'true'} if public else None)",
    '        return self._table',
    '',
    '    def _delta_batches(self, columns, clauses, any_of, limit=None):',
    '        # SQL over the table, a lookup as an IN so delta-rs skips files on their stats.',
    "        quote = lambda name: '\"' + name.replace('\"', '\"\"') + '\"'",
    '        literal = lambda v: str(v) if isinstance(v, int) else "\'" + str(v).replace("\'", "\'\'") + "\'"',
    "        sql = 'SELECT ' + (', '.join(map(quote, columns)) if columns else '*') + ' FROM t'",
    '        tests = [f\'{quote(name)} IN ({", ".join(map(literal, values))})\' for name, _, values in clauses if values]',
    '        if tests:',
    "            sql += ' WHERE ' + (' OR ' if any_of else ' AND ').join(tests)",
    '        if limit:',
    "            sql += f' LIMIT {int(limit)}'",
    "        return pa.RecordBatchReader.from_stream(QueryBuilder().register('t', self._delta()).execute(sql))",
    '',
    '    def names(self):',
    '        return self.schema().names',
    '',
    '    def read(self, columns=None, where=None, limit=None, text=True, any_of=False):',
    '        # text=False leaves the id columns as the file stores them, for a caller that groups by',
    '        # them before converting: 64-bit integers group far faster than a string per row.',
    '        # any_of: a row holding an id in any of the where columns, rather than in all of them.',
    '        schema = self.schema()',
    '        wanted = None if columns is None else list(dict.fromkeys(columns))',
    '        tested = [c for cols, _ in self.conditions for c in cols]',
    '        needed = None if wanted is None else list(dict.fromkeys(wanted + tested))',
    "        clauses = [(name, 'in', coda_typed_ids(ids, pa.types.is_integer(schema.field(name).type)))",
    '                   for name, ids in (where or {}).items()]',
    '        if clauses and (all if any_of else any)(not values for _, _, values in clauses):',
    '            table = schema.empty_table()',
    '        elif not clauses and limit:',
    '            # A cap with nothing to match: the first blocks, as the canvas reads, not the file.',
    '            table = self._head(needed, limit)',
    "        elif self.format == 'delta':",
    '            table = self._kept(self._delta_batches(needed, clauses, any_of).read_all())',
    "        elif self.format == 'parquet':",
    '            filters = [[c] for c in clauses if c[2]] if any_of else clauses',
    '            table = self._kept(pq.read_table(self._open(), columns=needed, filters=filters or None))',
    '        else:',
    '            names = None if needed is None else list(dict.fromkeys(needed + [c for c, _, _ in clauses]))',
    '            table = feather.read_table(self._open(), columns=names, memory_map=True)',
    '            masks = []',
    '            for name, _, values in clauses:',
    '                column = table[name]',
    '                if pa.types.is_dictionary(column.type):',
    '                    column = column.cast(column.type.value_type)',
    "                # Cast rather than built as the type: an id as text becomes a float column's",
    '                # number, where building one from text refuses.',
    '                masks.append(pc.is_in(column, value_set=pa.array(values).cast(column.type)))',
    '            if masks:',
    '                mask = masks[0]',
    '                for more in masks[1:]:',
    '                    mask = (pc.or_ if any_of else pc.and_)(mask, more)',
    '                table = table.filter(mask)',
    '            table = self._kept(table)',
    '        if wanted is not None:',
    '            table = table.select(wanted)',
    '        if limit:',
    '            table = table.slice(0, limit)',
    '        return (self._as_text(table) if text else table).to_pandas()',
    '',
    '    def _as_text(self, table):',
    "        # Arrow's own cast, before pandas sees the column: an int64 written digit for digit.",
    '        for name in self._text_columns() & set(table.column_names):',
    '            at = table.column_names.index(name)',
    '            table = table.set_column(at, name, table[name].cast(pa.string()))',
    '        return table',
    '',
    '    def _head(self, columns, limit):',
    '        batches, held = [], 0',
    "        if self.format == 'delta':",
    "            # The cap is the query's own where no condition drops rows after it, so the scan",
    '            # stops there rather than starting on every file at once.',
    '            source = self._delta_batches(columns, [], False, None if self.conditions else limit)',
    "        elif self.format == 'parquet':",
    '            source = pq.ParquetFile(self._open()).iter_batches(columns=columns)',
    '        else:',
    '            # Only the columns asked for are decoded, and over a URL only they are fetched.',
    '            names = self.schema().names',
    '            fields = None if columns is None else [names.index(c) for c in columns]',
    '            reader = pa.ipc.open_file(',
    '                self._open(), options=pa.ipc.IpcReadOptions(included_fields=fields))',
    '            source = (reader.get_batch(i) for i in range(reader.num_record_batches))',
    '        for batch in source:',
    '            # Counted after the conditions, as the canvas counts its cap in rows kept.',
    '            kept = self._kept(pa.Table.from_batches([batch]))',
    '            batches.append(kept)',
    '            held += kept.num_rows',
    '            if held >= limit:',
    '                break',
    '        return pa.concat_tables(batches) if batches else self.schema().empty_table()',
    '',
    '    def _kept(self, table):',
    '        # The conditions, on their columns as the canvas reads them — ids as text, whatever the',
    '        # caller asked of `text` — and the rows failing any dropped before anything else is done.',
    '        if not self.conditions:',
    '            return table',
    '        names = list(dict.fromkeys(c for cols, _ in self.conditions for c in cols))',
    '        frame = self._as_text(table.select(names)).to_pandas()',
    '        mask = pd.Series(True, index=frame.index)',
    '        for _, keep in self.conditions:',
    '            mask &= keep(frame).fillna(False).astype(bool)',
    '        return table.filter(pa.array(mask.to_numpy()))',
    '',
    '    def _text_columns(self):',
    '        # As the canvas read them where it had read the footer; otherwise the integer columns',
    "        # whose names say they are ids — Coda's own rule — so an id never arrives as int64.",
    '        if self.text_columns is None:',
    '            self.text_columns = {',
    '                field.name for field in self.schema()',
    '                if pa.types.is_integer(field.type) and coda_is_id_name(field.name)',
    '            }',
    '        return self.text_columns',
  ],
})

/**
 * A pandas frame with `CodaTableFile`'s reading surface, so a Custom Dataset reads a part one way
 * whether it was wired as a table or as a file — the `TableValue`/`TableFileValue` pair the canvas'
 * lookups already treat alike.
 */
registerHelper({
  name: 'CodaFrameTable',
  needs: ['coda_id_column', 'coda_typed_ids'],
  requires: [['pandas']],
  source: [
    'class CodaFrameTable:',
    '    """A pandas frame with `CodaTableFile`\'s reading surface, so a part is read one way whether',
    '    it was wired as a table or as a file."""',
    '',
    '    def __init__(self, frame):',
    '        self.frame = frame',
    '        self._keys = {}',
    '',
    '    def names(self):',
    '        return list(self.frame.columns)',
    '',
    '    def _key(self, name):',
    '        # A text key column converted once, not once per lookup.',
    '        if name not in self._keys:',
    '            self._keys[name] = coda_id_column(self.frame[name])',
    '        return self._keys[name]',
    '',
    '    def read(self, columns=None, where=None, limit=None, text=True, any_of=False):',
    '        # By position over the whole frame, never by label: a wired frame may repeat labels.',
    '        keep = None',
    '        for name, ids in (where or {}).items():',
    '            integer = pd.api.types.is_integer_dtype(self.frame[name])',
    '            key = self.frame[name] if integer else self._key(name)',
    '            hits = key.isin(coda_typed_ids(ids, integer)).to_numpy()',
    '            keep = hits if keep is None else (keep | hits if any_of else keep & hits)',
    '        frame = self.frame if keep is None else self.frame[keep]',
    '        if columns is not None:',
    '            frame = frame[list(dict.fromkeys(columns))]',
    '        return frame.head(limit) if limit else frame',
  ],
})

/**
 * navis 2's mesh class where it has one, `MeshNeuron` where it does not.
 *
 * `navis.Mesh` is navis 2's name, with `MeshNeuron` kept as a warning alias; PyPI's newest release
 * is still 1.12, which has only `MeshNeuron`. So a cell written against either name fails for half
 * its readers — `AttributeError` on a plain `pip install navis`, a deprecation warning on the git
 * build `export-requirements.txt` pins. Found by an audit: `check-export.py` resolved the name
 * against the git build and passed.
 */
registerHelper({
  name: 'coda_mesh',
  requires: [['navis']],
  source: [
    'def coda_mesh(*args, **kwargs):',
    '    """A navis mesh neuron: `navis.Mesh` in navis 2, `navis.MeshNeuron` before it."""',
    "    return (getattr(navis, 'Mesh', None) or navis.MeshNeuron)(*args, **kwargs)",
  ],
})

/**
 * A Neuroglancer precomputed bucket's geometry, through cloudvolume.
 *
 * cloudvolume rather than `navis.read_precomputed`: the latter reads a local directory, and a
 * bucket is a URL. Meshes are `coda_mesh` (`navis.Mesh`, or `MeshNeuron` before navis 2) at full
 * resolution, the canvas' default; a skeleton is built by `navis.edges2neuron`,
 * since navis will not take cloudvolume's `Skeleton` object itself. Both in nanometres, read off
 * the bucket's `info`. A batch that fails is **halved** until the segments with nothing are found,
 * so one missing segment costs a few requests rather than one per id; those are left out and
 * counted, as the canvas warns. Checked live against `gs://flywire_v141_m783`.
 */
registerHelper({
  name: 'CodaPrecomputed',
  needs: ['coda_mesh'],
  requires: [['cloudvolume', 'CloudVolume'], ['navis']],
  source: [
    'class CodaPrecomputed:',
    '    """A Neuroglancer precomputed bucket\'s geometry, through cloudvolume.',
    '',
    '    Meshes and skeletons come back as navis neurons in nanometres, which cloudvolume reads off',
    "    the bucket's `info`. A segment the bucket has nothing for is left out and counted, as the",
    '    canvas does.',
    '    """',
    '',
    '    def __init__(self, url):',
    '        self.url = url',
    '        self._cv = None',
    '',
    '    @property',
    '    def cv(self):',
    '        if self._cv is None:',
    '            self._cv = CloudVolume(self.url, use_https=True, progress=False)',
    '        return self._cv',
    '',
    '    def _each(self, ids, fetch, what):',
    '        # One request for the batch; a batch that fails is halved until the ids with nothing',
    '        # are found, so one missing segment costs a few requests rather than one per id.',
    '        def attempt(batch):',
    '            try:',
    '                return fetch(batch), []',
    '            except Exception as error:',
    '                if len(batch) == 1:',
    '                    errors.append(error)',
    '                    return {}, batch',
    '                half = len(batch) // 2',
    '                (a, lost_a), (b, lost_b) = attempt(batch[:half]), attempt(batch[half:])',
    '                return {**a, **b}, lost_a + lost_b',
    '',
    '        errors = []',
    '        ids = [int(i) for i in ids]',
    '        found, missing = attempt(ids) if ids else ({}, [])',
    '        if missing:',
    '            # Usually a segment with nothing in the bucket; the last error says if it was not.',
    "            print(f'{len(missing)} of {len(ids)} segments could not be read as {what} from '",
    "                  f'{self.url} (last error: {errors[-1]!r})')",
    '        return found',
    '',
    '    def meshes(self, ids):',
    "        found = self._each(ids, lambda batch: dict(self.cv.mesh.get(batch)), 'mesh')",
    '        return navis.NeuronList(',
    '            [coda_mesh(mesh, id=i, units="nm") for i, mesh in found.items()]',
    '        )',
    '',
    '    def skeletons(self, ids):',
    '        def fetch(batch):',
    '            return {int(s.id): s for s in self.cv.skeleton.get(batch)}',
    '',
    '        neurons = []',
    "        for i, sk in self._each(ids, fetch, 'skeleton').items():",
    '            tree = navis.edges2neuron(sk.edges, vertices=sk.vertices, validate=True)',
    '            tree.id = i',
    "            tree.units = 'nm'",
    '            neurons.append(tree)',
    '        return navis.NeuronList(neurons)',
  ],
})

/**
 * Coda's Custom Dataset: the parts, and the questions each answers — `CompositeSource` and the
 * wired edge set, ported.
 *
 * `labels` is the neuron table — `neuron_table` is `neuronTable` in `data/custom/neurons.ts` — or,
 * with none, the edge list's ids (`edgeListNeurons`). `connectivity` is `coda_walk` with a filter of
 * the edge list as its hop, and the canvas' `Include fragments`. `synapses` and `synapses_between`
 * are the lookups of `data/custom/synapses.ts`, positions scaled by the voxel size, `polarity` and
 * `confidence` left empty on the second for that module's reasons, and both ends pushed into one
 * read where both are bound. Geometry is a function of the ids per socket, which the emitter builds
 * at export from `geometryCall` — so a lender with no route is a note there, never a run-time error.
 */
registerHelper({
  name: 'CodaCustomDataset',
  needs: ['coda_id_column', 'coda_typed_ids', 'CodaTableFile', 'CodaFrameTable', 'coda_walk'],
  requires: [['pandas']],
  source: [
    'class CodaCustomDataset:',
    '    """Coda\'s Custom Dataset: a dataset assembled from parts, each answering its own questions.',
    '',
    '    `labels` is the neuron table — one row per neuron, keyed by text `neuronId` — or, with none',
    '    wired, every id the edge list mentions. `edges` and `synapses` name a frame or a',
    '    `CodaTableFile` and the columns Coda was told to read; with no edge list, connectivity is the',
    "    synapse table's rows counted per pair. `meshes` and `skeletons` are functions of the ids.",
    '    """',
    '',
    "    def __init__(self, neurons=None, id_column='neuronId', edges=None, synapses=None,",
    '                 meshes=None, skeletons=None):',
    '        self._labels = None if neurons is None else self.neuron_table(neurons, id_column)',
    '        self._labels_derived = neurons is None',
    '        self.edges = self._part(edges)',
    '        self.synapses_spec = self._part(synapses)',
    '        self.mesh_source = meshes',
    '        self.skeleton_source = skeletons',
    '        self._edge_list = None',
    '        self._type_map = None',
    '',
    '    @staticmethod',
    '    def _part(spec):',
    "        if spec is None or isinstance(spec['source'], CodaTableFile):",
    '            return spec',
    "        return {**spec, 'source': CodaFrameTable(spec['source'])}",
    '',
    '    @staticmethod',
    '    def neuron_table(frame, id_column):',
    '        """A table keyed by `id_column` as the neuron table: that column renamed neuronId and',
    '        read as text, first; rows with no usable id dropped, a repeated id\'s first row kept."""',
    '        ids = coda_id_column(frame[id_column]).values',
    "        rest = [c for c in frame.columns if c not in (id_column, 'neuronId')]",
    '        table = frame[rest].copy()',
    "        table.insert(0, 'neuronId', ids)",
    "        return table[table['neuronId'].notna()].drop_duplicates(subset='neuronId').reset_index(drop=True)",
    '',
    '    # ---- neurons ---------------------------------------------------------------------------',
    '',
    '    @property',
    '    def labels(self):',
    '        if self._labels is None:',
    '            if self.edges is None and self.synapses_spec is None:',
    '                raise ValueError(',
    "                    'This Custom Dataset has no neuron table, so it cannot say which neurons it '",
    "                    'has. Wire a table into Neurons, or an edge list into Edges.'",
    '                )',
    '            edges = self.edge_list()',
    "            ids = pd.unique(pd.concat([edges['preId'], edges['postId']], ignore_index=True))",
    "            self._labels = pd.DataFrame({'neuronId': ids})",
    '        return self._labels',
    '',
    '    def lookup(self, ids):',
    '        """The neuron table\'s rows for these ids — or, with none wired, the ids themselves.',
    '',
    '        With no neuron table nothing says which neurons there are, so nothing narrows the ids,',
    '        and nothing is read to find that out.',
    '        """',
    '        wanted = coda_typed_ids(ids, False)',
    '        if self._labels_derived:',
    "            return pd.DataFrame({'neuronId': list(dict.fromkeys(wanted))})",
    "        return self.labels[self.labels['neuronId'].isin(wanted)].reset_index(drop=True)",
    '',
    '    def _types(self):',
    '        if self._type_map is None:',
    '            # Ids read off the connections carry no type, and reading them to learn so would',
    '            # read a whole synapse table.',
    "            typed = not self._labels_derived and 'type' in self.labels.columns",
    "            self._type_map = (dict(zip(self.labels['neuronId'], self.labels['type']))",
    '                              if typed else {})',
    '        return self._type_map',
    '',
    '    # ---- connectivity ----------------------------------------------------------------------',
    '',
    '    def edge_list(self):',
    '        """Every connection as preId, postId, weight — ids as text, repeated pairs summed.',
    '',
    "        With no weight column every row counts one: a synapse table's rows, or an edge list whose",
    '        weight column is unnamed — or is the default `weight` and the list has none, which is',
    "        the canvas' reading of an untouched default.",
    '        """',
    '        if self._edge_list is None:',
    '            spec = self.edges or self.synapses_spec',
    '            if spec is None:',
    "                raise ValueError('This Custom Dataset has no connectivity. Wire an edge list '",
    "                                 'into its Edges socket, or a synapse table into Synapses.')",
    "            source = spec['source']",
    "            weight = self.edges.get('weight') if self.edges else None",
    '            if weight is not None and weight not in source.names():',
    "                print(f'The edge list has no column {weight!r}, so each row counts as one.')",
    '                weight = None',
    "            keys = [spec['pre'], spec['post']]",
    '            frame = source.read(columns=keys + ([weight] if weight else []), text=False)',
    '            # Per raw pair first, so ids are converted once per edge rather than once per row.',
    '            if weight:',
    "                frame = frame.assign(**{weight: pd.to_numeric(frame[weight], errors='coerce')})",
    '                pairs = frame.groupby(keys, sort=False)[weight].sum(min_count=1)',
    '            else:',
    '                pairs = frame.groupby(keys, sort=False).size()',
    "            pairs = pairs.reset_index(name='weight')",
    '            edges = pd.DataFrame({',
    "                'preId': coda_id_column(pairs[keys[0]]),",
    "                'postId': coda_id_column(pairs[keys[1]]),",
    "                'weight': pairs['weight'],",
    '            }).dropna()',
    '            if all(pd.api.types.is_integer_dtype(pairs[k]) for k in keys):',
    '                self._edge_list = edges.reset_index(drop=True)',
    '            else:',
    "                # Two raw spellings of one id (1 and ' 1') meet again after the cast.",
    "                self._edge_list = edges.groupby(['preId', 'postId'], as_index=False, sort=False)['weight'].sum()",
    '        return self._edge_list',
    '',
    '    def connectivity(self, seed_ids, direction, hops=1, min_weight=1, include_fragments=False):',
    '        """Coda\'s Connectivity node over the edge list: `coda_walk`, one hop a filter of it.',
    '',
    '        Without include_fragments a partner must be in the neuron table — seeds exempt, as on',
    '        the canvas; with no neuron table every id is in it.',
    '        """',
    '        edges = self.edge_list()',
    "        edges = edges[edges['weight'] >= min_weight]",
    '        seeds = set(coda_typed_ids(seed_ids, False))',
    '        keep = (None if include_fragments or self._labels_derived',
    "                else set(self.labels['neuronId']) | seeds)",
    '        types = self._types()',
    '',
    '        def one_hop(ids, way):',
    "            near, far = ('preId', 'postId') if way == 'downstream' else ('postId', 'preId')",
    '            step = edges[edges[near].isin(ids)]',
    '            if keep is not None:',
    '                step = step[step[far].isin(keep)]',
    "            return step.assign(preType=step['preId'].map(types), postType=step['postId'].map(types))",
    '',
    '        return coda_walk(seeds, direction, hops, one_hop)',
    '',
    '    # ---- synapses --------------------------------------------------------------------------',
    '',
    '    def _synapse_rows(self, where, carry=True, any_of=False):',
    "        \"\"\"The rows whose ends hold the ids asked about ({'pre': ids, 'post': ids}), ANDed",
    '        or, with any_of, either."""',
    '        spec = self.synapses_spec',
    '        if spec is None:',
    "            raise ValueError('This Custom Dataset has no synapses: wire a synapse table into its '",
    "                             'Synapses socket.')",
    "        carried = list(spec['carry']) if carry else []",
    '        # A carried column named like one this frame writes would overwrite it — a raw voxel',
    '        # `z` over the nanometre one. Left out, and said.',
    "        clashing = [c for c in carried if c in ('pre', 'post', 'x', 'y', 'z')]",
    '        if clashing:',
    "            print(f'Not carried, their names being taken by the position and ends: {clashing}')",
    '            carried = [c for c in carried if c not in clashing]',
    "        frame = spec['source'].read(",
    "            columns=[spec['pre'], spec['post'], *spec['position'], *carried],",
    '            where={spec[side]: ids for side, ids in where.items()},',
    '            any_of=any_of,',
    '        )',
    "        (vx, vy, vz), (x, y, z) = spec['voxel'], spec['position']",
    '        return pd.DataFrame({',
    "            'pre': coda_id_column(frame[spec['pre']]).values,",
    "            'post': coda_id_column(frame[spec['post']]).values,",
    "            'x': frame[x].astype(float).values * vx,",
    "            'y': frame[y].astype(float).values * vy,",
    "            'z': frame[z].astype(float).values * vz,",
    '            **{c: frame[c].values for c in carried},',
    '        })',
    '',
    '    def synapses(self, ids, polarity=None):',
    '        """A neuron set\'s synapses: neuronId the end asked about, partnerId the other, x/y/z in',
    '        nm, and the carried columns. One row per connection, both polarities unless one is asked."""',
    "        sides = [polarity] if polarity else ['pre', 'post']",
    '        # Both ends in one read, as the canvas does, then each end picked out of it — matched',
    '        # as text and as a number, since an integer column was matched numerically.',
    '        rows = self._synapse_rows({side: ids for side in sides}, any_of=True)',
    '        wanted = set(coda_typed_ids(ids, False)) | {str(i) for i in coda_typed_ids(ids, True)}',
    '        frames = []',
    '        for side in sides:',
    "            other = 'post' if side == 'pre' else 'pre'",
    '            frames.append(rows[rows[side].isin(wanted)]',
    "                          .rename(columns={side: 'neuronId', other: 'partnerId'})",
    '                          .assign(polarity=side))',
    '        out = pd.concat(frames, ignore_index=True)',
    "        first = ['neuronId', 'partnerId', 'polarity', 'x', 'y', 'z']",
    '        return out[first + [c for c in out.columns if c not in first]]',
    '',
    '    def synapses_between(self, sources=None, targets=None, include_fragments=True):',
    '        """The synapses from sources onto targets, oriented: neuronId is the presynaptic end.',
    '',
    '        polarity is left empty — a table holds one position per synapse and nothing says which',
    '        end it is at — and so is confidence, which the table carries no scale for. With one',
    '        side open and include_fragments off, its end is kept to the neuron table, as on the',
    '        canvas; with no neuron table there is nothing to keep it to.',
    '        """',
    "        where = {side: ids for side, ids in (('pre', sources), ('post', targets)) if ids is not None}",
    '        if not where:',
    "            raise ValueError('Synapses between two sets needs sources, targets or both.')",
    '        rows = self._synapse_rows(where, carry=False)',
    '        if not include_fragments and len(where) == 1 and not self._labels_derived:',
    "            open_end = 'post' if 'pre' in where else 'pre'",
    "            rows = rows[rows[open_end].isin(self.labels['neuronId'])].reset_index(drop=True)",
    '        types = self._types()',
    '        return pd.DataFrame({',
    "            'neuronId': rows['pre'].values,",
    "            'type': rows['pre'].map(types).values,",
    "            'partnerId': rows['post'].values,",
    "            'partnerType': rows['post'].map(types).values,",
    "            'polarity': None,",
    "            'confidence': None,",
    "            'x': rows['x'].values,",
    "            'y': rows['y'].values,",
    "            'z': rows['z'].values,",
    '        })',
    '',
    '    # ---- geometry --------------------------------------------------------------------------',
    '',
    '    def _geometry(self, source, what, ids):',
    '        if source is None:',
    "            raise ValueError(f'This Custom Dataset has no {what} in this notebook: nothing is '",
    "                             f'wired into its {what.capitalize()} socket, or what is wired there '",
    "                             f'has no notebook form (the Custom Dataset cell says so).')",
    '        return source(ids)',
    '',
    '    def meshes(self, ids):',
    "        return self._geometry(self.mesh_source, 'meshes', ids)",
    '',
    '    def skeletons(self, ids):',
    "        return self._geometry(self.skeleton_source, 'skeletons', ids)",
  ],
})
