/**
 * Reading somebody else's Wavefront OBJ.
 *
 * The counterpart to the OBJ *writing* in `ui/exportValue.ts`, and it sits here beside `csv.ts`
 * for the same reason that one does: it is a format, not a backend. neuPrint serves its region
 * meshes as OBJ; FlyWire and CAVE are the obvious next callers, and none of them should each
 * grow a parser.
 *
 * ## What real files made this handle
 *
 * Every rule below came out of the files neuPrint actually serves rather than from the spec, and
 * the datasets disagree with each other:
 *
 *  - **hemibrain** publishes `# OBJ File Generated by Meshlab` with **no normals**, faces written
 *    as bare `f 1 2 3`.
 *  - **male-CNS, MANC and optic-lobe** publish `# OBJ file` **with** a normal per vertex, faces
 *    written as `f 1//1 2//2 3//3`.
 *
 * A parser that assumed the bare form would read a *normal* index as a vertex index on three of
 * the four datasets — and, because the counts happen to match, it would not fail. It would build
 * a mesh out of the right number of triangles connecting the wrong points, which renders as a
 * shredded blob and blames the renderer.
 *
 * ## What is deliberately dropped
 *
 * Normals and texture coordinates. Nothing here shades a region mesh — the outline comes from
 * rasterising triangles — so keeping a normal per vertex would double the memory of a 51,000
 * vertex neuropil for data nobody reads. A consumer that ever needs them should recompute from
 * the faces, which is what every renderer does anyway.
 *
 * Materials, groups and objects are skipped too. A region mesh is one object by construction,
 * and merging groups is exactly what a caller wants from a file that has them.
 */

export interface ObjMesh {
  /** xyz interleaved, in the file's own units. */
  positions: Float32Array
  /** Triangle indices into `positions`. */
  indices: Uint32Array
  /** How many source faces had more than three corners and were fanned. */
  polygons: number
  /** Face corners that named a vertex the file never declared. */
  dropped: number
}

const EMPTY: ObjMesh = {
  positions: new Float32Array(0),
  indices: new Uint32Array(0),
  polygons: 0,
  dropped: 0,
}

/**
 * Parse an OBJ into flat typed arrays.
 *
 * Never throws. A file that is not an OBJ at all — an HTML error page served with a 200, which
 * is the usual way this fails — parses to zero vertices, and the caller is expected to say so
 * in terms somebody can act on. Throwing here would have every caller catch and re-word it.
 */
export function parseObj(text: string): ObjMesh {
  if (!text) return EMPTY

  const positions: number[] = []
  const indices: number[] = []
  let polygons = 0
  let dropped = 0

  // Reused across faces so a 100,000-face file does not allocate one array per triangle fan.
  const corners: number[] = []

  for (const rawLine of text.split('\n')) {
    // `\r` survives a file written on Windows and turns the last number of every line into NaN.
    const line = rawLine.trim()
    if (line.length === 0 || line.charCodeAt(0) === 35 /* # */) continue

    if (line.startsWith('v ')) {
      const parts = line.slice(2).trim().split(/\s+/)
      // A `v` may carry a fourth weight component and, in some exporters, three colour channels.
      // Only the first three are the position.
      positions.push(Number(parts[0]), Number(parts[1]), Number(parts[2]))
      continue
    }

    if (!line.startsWith('f ')) continue

    corners.length = 0
    const vertexCount = positions.length / 3
    for (const token of line.slice(2).trim().split(/\s+/)) {
      if (token.length === 0) continue
      // `v`, `v/vt`, `v//vn`, `v/vt/vn` — the vertex index is always the first field.
      const slash = token.indexOf('/')
      const raw = Number(slash === -1 ? token : token.slice(0, slash))
      if (!Number.isFinite(raw) || raw === 0) {
        dropped++
        continue
      }
      // OBJ indices are 1-based; a negative one counts back from the vertices seen so far.
      const index = raw > 0 ? raw - 1 : vertexCount + raw
      if (index < 0 || index >= vertexCount) {
        dropped++
        continue
      }
      corners.push(index)
    }

    if (corners.length < 3) continue
    if (corners.length > 3) polygons++
    // Fan from the first corner. Correct for any convex face, and the concave case it gets
    // wrong is a self-overlapping polygon no mesh exporter emits.
    for (let i = 1; i + 1 < corners.length; i++) {
      indices.push(corners[0]!, corners[i]!, corners[i + 1]!)
    }
  }

  /*
   * A file with vertices and no faces keeps its vertices, and that is not tidiness: it is the
   * only thing that distinguishes a point cloud from an error page, and `objProblem` reports
   * those as different problems. Collapsing both to "empty" made it say "no vertices" about a
   * file that plainly had them.
   */
  if (positions.length === 0 || indices.length === 0) {
    return {
      positions: positions.length > 0 ? Float32Array.from(positions) : EMPTY.positions,
      indices: new Uint32Array(0),
      polygons,
      dropped,
    }
  }

  return {
    positions: Float32Array.from(positions),
    indices: Uint32Array.from(indices),
    polygons,
    dropped,
  }
}

/**
 * What went wrong, in a sentence somebody can act on — or undefined when nothing did.
 *
 * Separate from the parse because the parse cannot know what it was asked for. "No vertices"
 * from a region mesh endpoint overwhelmingly means an error page arrived with a 200, and quoting
 * the first line of what did arrive is the difference between a fixable report and a shrug.
 */
export function objProblem(mesh: ObjMesh, text: string, what: string): string | undefined {
  if (mesh.positions.length > 0 && mesh.indices.length > 0) return undefined
  const head = text.trim().slice(0, 80).replace(/\s+/g, ' ')
  if (!head) return `${what} came back empty.`
  if (mesh.positions.length === 0) {
    return `${what} is not a mesh — no vertices in ${text.length} bytes starting "${head}".`
  }
  return `${what} has ${mesh.positions.length / 3} vertices but no faces.`
}
