/**
 * The shared SWC walk and the file parser, offline.
 *
 * The fixture is **real bytes** — the head of `AL-VA1v` body 1010's `1010_swc`, NeuTu's own
 * output including the `#<json>…</json>` header line it writes among the comments. Nothing here
 * is invented, because the two things worth pinning are exactly the two that a hand-written
 * fixture would get wrong by construction: that the comment lines are survivable, and that the
 * coordinates arrive in **voxels** and leave in nanometres.
 *
 * Beside `swc.ts` rather than under `data/dvid/`, because the walk is shared with neuPrint's
 * reader — filed under one of two callers is where the other one's owner never finds it
 * (`docs/testing-layers.md`). What is DVID-specific is only that the fixture came from there.
 *
 * Offline while the mesh decode is live for a reason about the servers, not the code: no public
 * DVID has both the `<segmentation>_skeletons` convention resolving *and* a populated store.
 * `dvid/live.test.ts` covers what is live-checkable — the refusal, and opening a real store with
 * a real scale.
 */

import { describe, expect, it } from 'vitest'

import { parseSwcText } from './swc'
import { scaleRadii, scalePositions } from './units'

/** The head of `1010_swc` as NeuTu wrote it, comments included. */
const SWC = `#Generated by NeuTu (https://github.com/janelia-flyem/NeuTu)
#<json>{"ds_intv": [7, 7, 7], "min_length": 40.0}</json>
1 0 3078 8702 8696 36 -1
2 0 3086 8758 8648 69.7564 1
3 0 3142 8878 8504 67.5542 2
4 0 3230 8918 8376 52 3
`

describe('parsing DVID’s SWC', () => {
  it('skips the comment header NeuTu writes, including its JSON line', () => {
    const skeleton = parseSwcText('1010', SWC)
    expect(skeleton.parents.length).toBe(4)
    expect(skeleton.id).toBe('1010')
  })

  it('resolves link-by-row-id into parent-before-child indices', () => {
    // `link` names a row id, not an index, and every consumer that walks a skeleton assumes a
    // parent appears before its child. The shared walk in `data/swc.ts` is what guarantees it.
    const skeleton = parseSwcText('1010', SWC)
    expect([...skeleton.parents]).toEqual([-1, 0, 1, 2])
  })

  it('keeps the file’s voxels, leaving the scale to whoever knows the voxel size', () => {
    const skeleton = parseSwcText('1010', SWC)
    expect([...skeleton.positions.subarray(0, 3)]).toEqual([3078, 8702, 8696])
    expect(skeleton.radii[0]).toBe(36)
  })

  it('multiplies to nanometres by the segmentation’s own voxel size', () => {
    /*
     * The silent failure this whole path is shaped around. `AL-VA1v` is 8 nm isotropic, so body
     * 1010's first node is 24,624 nm — and the same body's *mesh* spans 18,043…91,635 nm, which
     * is the range these voxels land in once multiplied. Unscaled the skeleton draws at 1/8
     * inside that mesh with a cable length 8× short, and nothing fails.
     */
    const skeleton = parseSwcText('1010', SWC)
    expect([...scalePositions(skeleton.positions, [8, 8, 8]).subarray(0, 3)]).toEqual([
      24624, 69616, 69568,
    ])
    // Radii go the same way, by `units.ts`' mean rule — the two must not diverge, or the header
    // `exportValue.ts` writes onto every saved SWC stops being true.
    expect(scaleRadii(skeleton.radii, [8, 8, 8])[0]).toBe(288)
  })

  it('drops a malformed node rather than defaulting it to the origin', () => {
    // A short line is a broken node, and defaulting its coordinates would draw a stray segment
    // through the middle of the neuron — a wrong picture rather than a missing one.
    const skeleton = parseSwcText('1', '1 0 1 2 3 4 -1\n2 0 5 6\n3 0 7 8 9 1 1\n')
    expect(skeleton.parents.length).toBe(2)
    expect([...skeleton.positions]).toEqual([1, 2, 3, 7, 8, 9])
  })

  it('keeps the points of an unrooted cycle rather than losing them', () => {
    /*
     * Two rows linking to each other, so the traversal never reaches them. The fallback pass
     * emits each as its own root: connectivity within the cycle is lost, which is the honest
     * price of terminating, and half a neuron vanishing silently would be worse. `data/swc.ts`
     * owns the rule and both front ends inherit it — this is neuPrint's long-standing behaviour,
     * pinned here because the DVID path is now a second caller of it.
     */
    const skeleton = parseSwcText('1', '1 0 0 0 0 1 2\n2 0 1 1 1 1 1\n')
    expect([...skeleton.parents]).toEqual([-1, -1])
    expect([...skeleton.positions]).toEqual([0, 0, 0, 1, 1, 1])
  })
})
